### ISSUE TITLE
启动出了多个实例

### ISSUE THREAD

**Issue by lsrweb** [1111mp/nvm-desktop#101]
在使用 utools 工具的时候会拉起多个应用实例

先启动一个,再通过utools启动一个,又能拉起一个,能拉起很多个
通过桌面快捷方式也可以拉起多个应用实例

![image](https://github.com/user-attachments/assets/5025b199-9522-4c78-9af8-700b43f86478)
![image](https://github.com/user-attachments/assets/185ce2b4-f3c7-4f97-be5a-e3bceddf6d5f)

**Comment by 1111mp** [comment]
好的 知道是什么原因造成的了 在调用 createWindow 方法的时候没有判断窗口和系统托盘是否存在直接执行了 所以会出现这个问题 谢谢你的反馈 下个小版本会修复这个问题 谢谢 🌹

**Comment by lsrweb** [comment]
让 nvmd-desktop 伟大!!!!!!!!!!!!
我现在离不开nvmd 了,太好用了,期望它越来越好

**Comment by 1111mp** [comment]
@tzwhyqq 系统高级设置 然后点击环境变量 双击打开系统环境变量path 然后点击新建 然后将 `.nvmd\bin` 所在目录完整地址复制粘贴进去 然后点击确定 应用保存 之后终端或者vscode 需要重启
![image](https://github.com/user-attachments/assets/ec810b84-cf8d-4130-ba7b-20eaade9b0eb)
![image](https://github.com/user-attachments/assets/52eddde0-4ca6-4da8-9089-bd428457af36)
![image](https://github.com/user-attachments/assets/6f400049-a803-4a39-815d-c2b8b4d77471)

**Comment by 1111mp** [comment]
- 修改当前会话的 $env:PATH
```shell
$env:NVMD_HOME = $gradleHome
$env:PATH += ";$gradleHome\bin"
```

- 使用 Invoke-Expression 强制 PowerShell 重新加载环境变量
```shell
$env:NVMD_HOME = $gradleHome
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::User) + ";$env:NVMD_HOME\bin"
```

- 如果你安装了 [Chocolatey](https://chocolatey.org/) 包管理器，那么可以使用 `refreshenv` 命令来刷新环境变量
```shell
refreshenv
```

我也是现学现卖 你看看能不能帮助到你

**Comment by lsrweb** [comment]
谢谢,我去尝试一下
________________________________
发件人: The1111mp ***@***.***>
发送时间: 2024年8月29日 11:23
收件人: 1111mp/nvm-desktop ***@***.***>
抄送: Lisa Feaster ***@***.***>; Author ***@***.***>
主题: Re: [1111mp/nvm-desktop] 启动出了多个实例 (Issue #101)


  *   修改当前会话的 $env:PATH

$env:NVMD_HOME = $gradleHome
$env:PATH += ";$gradleHome\bin"

  *   使用 Invoke-Expression 强制 PowerShell 重新加载环境变量

$env:NVMD_HOME = $gradleHome
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::User) + ";$env:NVMD_HOME\bin"

  *   如果你安装了 Chocolatey<https://chocolatey.org/> 包管理器，那么可以使用 refreshenv 命令来刷新环境变量

refreshenv

我也是现学现卖 你看看能不能帮助到你

―

**Comment by tzwhyqq** [comment]
我又来求助，刚才那个问题好了。现在 我单独在 powershell 里面可以执行， 在 idea 或者vs 里面 就是没反应。
![微信图片_20240829131340](https://github.com/user-attachments/assets/51d6dada-4999-429d-bc14-310f7847a059)
试过 卸载了重新弄，还是有问题，要崩溃，这个win11 问题真多。

**Comment by tzwhyqq** [comment]
我都不知道它怎么跑到这个 vueproject 目录，。我都没在安装在这个目录

**Comment by tzwhyqq** [comment]
我的安装目录 D:\Program Files\nvm-desktop

**Comment by tzwhyqq** [comment]
没事了。解决了。环境变量换成  大佬你给的 绝对路径就好，我原先用了 %HOMEXXXX% 那样就不行
