### ISSUE TITLE
为什么安装以后powershell不能使用了 输入cmd以后报错

### ISSUE THREAD

**Issue by xuzhoulong** [1111mp/nvm-desktop#103]
![IMG_20240801_180917](https://github.com/user-attachments/assets/64d1d650-c6fa-472c-a028-6cedb04cdc73)

**Comment by LaTaXiaoPengYou** [comment]
我感觉是删除%HOMEPATH%\.nvmd\bin这个的时候误把path里面的所有变量都删了，可是已经不知道里面原来的变量有什么了怎么办

**Comment by LaTaXiaoPengYou** [comment]
> 应该是 没有添加到系统环境变量里面去 你检查一下呢`C:\Windows\System32`

我感觉是删除%HOMEPATH%.nvmd\bin这个的时候误把path里面的所有变量都删了，可是已经不知道里面原来的变量有什么了怎么办

**Comment by 1111mp** [comment]
只能一个个加回来了 你试试网上搜一下呢 我也不知道你安装过多少软件。。

**Comment by LaTaXiaoPengYou** [comment]
> 只能一个个加回来了 你试试网上搜一下呢 我也不知道你安装过多少软件。。

软件的倒无所谓
就是我担心系统的默认一些变量没了 然后电脑死翘翘了

**Comment by 1111mp** [comment]
你可以网上搜一下默认的环境变量有哪些，或者找一台其他电脑，对比加一下就好

**Comment by tzwhyqq** [comment]
win11  用pnpm 一直 报   EPERM: operation not permitted, symlink 。   查了下，说是node 没权限。还是不行，有没有解决办法。

**Comment by tzwhyqq** [comment]
再修改的时候，安装了node最新版本 然后把旧的删除了。 出现  node: The term 'node' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by 1111mp** [comment]
> 在解決pnpm权限的问题的时候，先安装了node最新版本 然后把旧的删除了。 出现 node: The term 'node' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 去.nvmd 下查看 nvmd.exe 文件没有了。复制了一份新的也没用。 没解了。。。

感觉是环境变量没有添加正确 试试使用cmd终端执行试试呢
