### ISSUE TITLE
【体验优化】针对Windows 平台，最小化和关闭窗口应该放置在右边

### ISSUE THREAD

**Issue by yxw007** [1111mp/nvm-desktop#104]
软件设计的很棒，但是如果是windows用户会非常不习惯往左边去点关闭窗口和最小话窗口，这个体验应该随系统一致，避免给用户带来困扰

**Comment by 1111mp** [comment]
抱歉这么久才回复  这个体验问题后面我会优化一下 谢谢提出来

**Comment by yxw007** [comment]
> 抱歉这么久才回复 这个体验问题后面我会优化一下 谢谢提出来

没关系，开源不易，深表理解。😊

**Comment by 1111mp** [comment]
最新的 3.4.0 版本已经将最小化和关闭按钮移动到右边了 请更新到最新版本体验 
那么这个issue就先关闭了 谢谢

**Comment by yxw007** [comment]
> 最新的 3.4.0 版本已经将最小化和关闭按钮移动到右边了 请更新到最新版本体验 
> 
> 那么这个issue就先关闭了 谢谢

nice，辛苦了
