### ISSUE TITLE
linux怎么装

### ISSUE THREAD

**Issue by lsy934127847** [1111mp/nvm-desktop#105]

**Comment by lsy934127847** [comment]
linux : 报错： [0816/150014.084477:FATAL:electron_main_delegate.cc(295)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap (core dumped)

**Comment by 1111mp** [comment]
是在终端通过命令行 `sudo ./nvm-desktop` 来启动的吗 根据提示你只能通过 `./nvm-desktop` 或者 `sudo ./nvm-desktop --no-sandbox` 来启动项，这个应该是 Chromium 的安全策略。
