### ISSUE TITLE
TimeoutError:Timeout awaiting 'request'for 20000ms

### ISSUE THREAD

**Issue by hymnlongworker** [1111mp/nvm-desktop#106]
![image](https://github.com/user-attachments/assets/c8cd93fc-2f5b-407d-94c1-e50ebf783f6b)
TimeoutError:Timeout awaiting 'request'for
20000ms

**Comment by 1111mp** [comment]
试试这个镜像地址呢：https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/

**Comment by hymnlongworker** [comment]
> 试试这个镜像地址呢：https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/

这个地址可以
