### ISSUE TITLE
Windows11启动报错

### ISSUE THREAD

**Issue by GeniusJerry** [1111mp/nvm-desktop#108]
![image](https://github.com/user-attachments/assets/aa197938-a8fc-4ed9-9df9-6c000666af3b)
window11启动报错

**Comment by 1111mp** [comment]
请问这边使用的是哪个版本

**Comment by GeniusJerry** [comment]
> 请问这边使用的是哪个版本

![image](https://github.com/user-attachments/assets/4106a11e-7c6f-4edd-b5b3-9a123ada1f0a)
我重新下载的最新的3.3.0，没问题了

**Comment by GeniusJerry** [comment]
![image](https://github.com/user-attachments/assets/aa877348-ddcc-4d35-bacd-2cb4d6bde848)
我用你们这个软件切换node后，执行npm语法会报这个错误，比如我执行npm install -g yarn

**Comment by GeniusJerry** [comment]
![image](https://github.com/user-attachments/assets/26a3d2e7-547c-4bbd-8e20-0b4e6cf91c91)
我看了确实这个目录缺少nvmd.exe

**Comment by 1111mp** [comment]
> > 请问这边使用的是哪个版本
> 
> 帮忙看看我上边发的nvmd的问题

临时的解决方法是直接复制一份 node.exe 重命名为 nvmd.exe 即可

请问是使用的最新版本吗 理论上这个问题已经修复了

**Comment by GeniusJerry** [comment]
> > > 请问这边使用的是哪个版本
> > 
> > 
> > 帮忙看看我上边发的nvmd的问题
> 
> 临时的解决方法是直接复制一份 node.exe 重命名为 nvmd.exe 即可
> 
> 请问是使用的最新版本吗 理论上这个问题已经修复了

3.3.0呀，没办法了我临时把你们软件卸载了

**Comment by 1111mp** [comment]
最新3.4.0版本已经针对这个问题采取了进一步修复措施 可以更新到最新版本体验 那么这个issue就先关闭了 谢谢 当然有问题也可以随时重新打开
