### ISSUE TITLE
提个小建议：版本锁定在package中

### ISSUE THREAD

**Issue by Lingtin** [1111mp/nvm-desktop#11]
<img width="242" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/25638355/b0e76435-fb57-4ff5-bd73-4acd971a2102">
<img width="430" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/25638355/1668ac80-d6bc-42db-8d7e-7924b7d20978">

大佬提个建议，能不能使用volta的方式，把版本锁定在package中

**Comment by 1111mp** [comment]
其实无论是保存在`package.json`还是`.nvmdrc`中都是有利有弊的，之所以没有放在`package.json`中是因为考虑了有些项目其实没有用到该文件（比如一些单纯的js脚本，或者其他语言需要用到了js脚本...等需要指定npde版本），然后还有项目涉及多人合作的时候可以直接通过在`.gitignore`中可以直接忽略`.nvmdrc`文件，不会有其他副作用，最后就是想尽量减少对其它的依赖......

所以最终就是选择放在`.nvmdrc`文件中了。望理解。

**Comment by Lingtin** [comment]
<img width="596" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/25638355/637b4b91-e635-4e5c-8d1d-ae8682ed6300">
使用npm i -g yarn，安装的yarn或者是nrm在终端执行都找到，查看了~/.nvmd目录中对于的版本确实是有yarn这个包下载的，就是命令找不到，这个怎么解决啊

**Comment by Lingtin** [comment]
<img width="745" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/25638355/1a5e6ea6-e103-4903-abc7-e45856488923">
<img width="475" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/25638355/5ec540a4-8646-4365-8011-7b6e682bffde">
这是我的目录，已知是有包的，但是没有映射

**Comment by 1111mp** [comment]
我想我应该知道是什么问题了，你试试使用npm install -g yarn 命令重新安装试试呢 使用install全称安装 我好像没有考虑到缩写形式
如果还是有问题的话试试前面加上sudo 或者提供一下nvm-desktop的版本 以及执行一下 nvmd -h 命令查看命令行工具是否正常

抱歉

**Comment by Lingtin** [comment]
<img width="743" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/25638355/7ba9d800-db7e-4549-b737-1fe3fa735d25">

重新使用npm install -g xxx 命令安装，是可以有记录的。这边就是应该是缩写的问题了。

**Comment by 1111mp** [comment]
谢谢你的反馈，问题我已经记录下来了，下个小版本会修复这个问题。  

感谢。

**Comment by 1111mp** [comment]
已经在[Release v2.4.0](https://github.com/1111mp/nvm-desktop/releases/tag/v2.4.0)中修复。

如果有问题请随时打开此问题。
