### ISSUE TITLE
MAC M1安装之后显示zsh: permission denied: nvmd

### ISSUE THREAD

**Issue by constown** [1111mp/nvm-desktop#113]
![image](https://github.com/user-attachments/assets/97c7d685-8368-4e4e-aeef-822e29f3dfae)
程序可以正常运行，但是使用nvmd  node等命令都报permission denied

![image](https://github.com/user-attachments/assets/2c668a87-7416-46be-93e5-da916171d131)
 也都有配置

<img width="570" alt="image" src="https://github.com/user-attachments/assets/3c6a618a-4410-482c-8f1a-d2a40c73a8aa">

**Comment by 1111mp** [comment]
应该是nvmd没有权限 可以进入 `$HOME/.nvmd/bin` 目录下执行 `sudo chmod +x nvmd` 赋予一下权限

**Comment by constown** [comment]
> 应该是nvmd没有权限 可以进入 `$HOME/.nvmd/bin` 目录下执行 `sudo chmod +x nvmd` 赋予一下权限

可以了，但是我在以前（具体哪个版本没有记）好像并没有遇到这个问题，然后很久没更新了，更新到4.0.0版本出现了这个。

**Comment by 1111mp** [comment]
你的设备应该是macos m系列芯片吧 4.0版本之后打包涉及到跨平台交叉编译 然后加上代码并没有签名 所以macos上的安全策略默认是不给权限运行的 这个目前需要用户自己手动允许一下

**Comment by constown** [comment]
> 你的设备应该是macos m系列芯片吧 4.0版本之后打包涉及到跨平台交叉编译 然后加上代码并没有签名 所以macos上的安全策略默认是不给权限运行的 这个目前需要用户自己手动允许一下

是的 M1 芯片。

**Comment by 1111mp** [comment]
之前的 nvmd 可执行文件是在我自己设备上编译的（m1 芯片） 现在打包编译都是有 github action 托管来自动化的 可能的原因是涉及到跨架构的交叉编译导致这个问题 我会试试下个版本macos平台走自己本地设备打包 看后续还会不会有这个问题
