### ISSUE TITLE
MacOS15 提示文件以损坏

### ISSUE THREAD

**Issue by nap-yu** [1111mp/nvm-desktop#114]
![Uploading image.png…]()

**Comment by 1111mp** [comment]
请查看一下这里的文档： [Fix 'File/App is damaged and cannot be opened' on Mac](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#macos-issues) 看是否能够帮助到你 谢谢

**Comment by 1111mp** [comment]
这个问题很久没有反馈，通过文档应该能够解决，我先关闭此问题。后续有问题可以随时重新开启。谢谢。
