### ISSUE TITLE
[BUG] 更新按钮报错

### ISSUE THREAD

**Issue by lsrweb** [1111mp/nvm-desktop#115]
![image](https://github.com/user-attachments/assets/1e264410-4606-4eac-84de-79c8ea279a34)

**Comment by lsrweb** [comment]
补一句 4.0 tauri 版本的

**Comment by 1111mp** [comment]
自动更新是检查 [releases/tag/updater/update.json](https://github.com/1111mp/nvm-desktop/releases/tag/updater) 文件来判断是否有更新的 是不是因为访问不了 github 服务所以才导致这个问题的
