### ISSUE TITLE
[BUG]安装的时候报系统找不到指定的路径

### ISSUE THREAD

**Issue by oo10** [1111mp/nvm-desktop#117]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Arch: [e.g. arm64]
 - Version [e.g. 4.0.0]

**Additional context**

---

**描述错误**
清晰简明地描述错误是什么。

**重现步骤**
重现该行为的步骤：
1. 进入 '...'
2. 点击 '....'
3. 向下滚动到 '....'
4. 看到错误

**预期行为**
清晰简明地描述你期望发生的事情。
我使用的是内网的node源。
预期能够成功安装。

**截图**
如果适用，请添加截图以帮助解释您的问题。
<img width="496" alt="image" src="https://github.com/user-attachments/assets/28cf1f85-0f52-4e24-a5bc-59733c531840">

**桌面设备（请填写以下信息）：**
 - 操作系统: [例如 macOS]
 - 架构: [例如 arm64]
 - 版本: [例如 4.0.0]

**附加上下文**
在此添加有关问题的任何其他上下文。

**Comment by 1111mp** [comment]
请问目前使用的是哪个版本呢 点击下载之后 有进度条吗 还是直接就提示失败 或者下载成功了（进度条）最后解压阶段失败

**Comment by oo10** [comment]
> 请问目前使用的是哪个版本呢 点击下载之后 有进度条吗 还是直接就提示失败 或者下载成功了（进度条）最后解压阶段失败

使用的4.0.0
点击安装后按钮loading，10s左右后提示失败。没有看到进度条
<img width="689" alt="image" src="https://github.com/user-attachments/assets/00204890-f2ff-494d-99b8-c492a3d9c3f2">

**Comment by 1111mp** [comment]
好的 已经定位到问题了 下载时安装目录不存在时应该先创建该目录 后面我会修复一下这个问题 然后重新编译一下 编译好了会在这里跟你说一下 因为还没有发正式版 所以还是需要你重新下载重新安装一下 抱歉

**Comment by 1111mp** [comment]
已经重新发布了 重新下载安装一下呢 最好是先手动把 `%HOMEPATH%\.nvmd` 整个文件夹都删掉 然后安装启动 应该就好了

**Comment by oo10** [comment]
> 已经重新发布了 重新下载安装一下呢 最好是先手动把 `%HOMEPATH%\.nvmd` 整个文件夹都删掉 然后安装启动 应该就好了

@1111mp 赞，响应好快!!! 但是默默问一句 要去哪里下载最新的这个版本呀。github release 好像还是3周前~~~~ 谢谢

**Comment by 1111mp** [comment]
https://github.com/1111mp/nvm-desktop/releases/tag/v4.0.0-alpha 这里下载 4.0.0 版本的 目前还处于alpha阶段使用tauri重构的 目前还处于alpha阶段 等后面稳定了 发布release版本了 就不需要手动下载了 windows和macos 都支持自动更新的功能

**Comment by oo10** [comment]
> https://github.com/1111mp/nvm-desktop/releases/tag/v4.0.0-alpha 这里下载 4.0.0 版本的 目前还处于alpha阶段使用tauri重构的 目前还处于alpha阶段 等后面稳定了 发布release版本了 就不需要手动下载了 windows和macos 都支持自动更新的功能

安装成功了,但是 node 好像没生效
<img width="853" alt="image" src="https://github.com/user-attachments/assets/59cb9614-873f-48a8-83f0-90c46aa3819d">

**Comment by 1111mp** [comment]
需要确认一下 系统环境变量 确保 %HOMEPATH%\.nvmd\bin 在你安装的node的前面

**Comment by oo10** [comment]
> 需要确认一下 系统环境变量 确保 %HOMEPATH%.nvmd\bin 在你安装的node的前面

已解决 感谢 ！

**Comment by 1111mp** [comment]
问题解决了就好

那我就先把这个issue关掉了 当然后续如果有任何问题都可以随时重新打开 谢谢
