### ISSUE TITLE
新电脑安装 tauri 4.0报了个错误

### ISSUE THREAD

**Issue by lsrweb** [1111mp/nvm-desktop#118]
![image](https://github.com/user-attachments/assets/60b93263-fe97-4974-9f84-ad28dabf5494)

**Comment by lsrweb** [comment]
原来是缺少微软运行库

**Comment by 1111mp** [comment]
是的 这个错误很常见 electron 也一样 需要手动安装一下运行库：[vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)
