### ISSUE TITLE
[FEATURE]请支持配置网络代理

### ISSUE THREAD

**Issue by ZimaBlueee** [1111mp/nvm-desktop#119]
公司内网环境，软件默认无法访问互联网，需要配置http代理才能让软件联外网，例如下图IDEA里支持的http代理。

这个软件真是太棒了，目前遇到的同类产品No.1，希望作者大大可以考虑代理功能

![图片](https://github.com/user-attachments/assets/e673aa36-8ea6-4966-885d-b0ef5e7b74d7)

**Comment by 1111mp** [comment]
谢谢支持🙏
设置里面有代理的功能，3.4.0版本开始支持的，你可以用一下看看，如果有什么问题可以随时反馈，谢谢

**Comment by ZimaBlueee** [comment]
刚更新了3.4，代理功能确实有了！！

但有个小问题：

我公司电脑，给软件配置了代理，能刷新出更新的node版本（22），但下载到最后的时候会报错，如下图：
 
![图片](https://github.com/user-attachments/assets/d783f457-1a58-4f40-8473-f8e4871411b9)

我家里的电脑，软件没配置代理，可以正常下载，但是无法刷新出node版本，最新的node版本还是21，如下图：

![图片](https://github.com/user-attachments/assets/2e5e2761-8966-4966-a020-71538766f5e0)


2个电脑上的软件用的镜像地址都是https://npmmirror.com/mirrors/node

如果需要我提供报错信息，请教我一下怎么查看异常日志。任何问题请继续询问。

祝好！

**Comment by 1111mp** [comment]
刚确认了一下代码，在文件下载完成之后的文件完整性验证上没有应用配置的代理造成了验证失败，你可以试试4.0 alpha版本吗，需要在github release页面下手动下载一下，这个是后面主要支持的版本，望理解（这几天稳定下来就会发布4.0 release版本出来）

**Comment by 1111mp** [comment]
从 [Release 4.0.0](https://github.com/1111mp/nvm-desktop/releases/tag/v4.0.0) 版本开始已经支持配置代理 那么这个问题我就先关闭了 当然如果有其它问题也可以随时打开这个issue 谢谢
