### ISSUE TITLE
程序的安装位置和node的默认安装位置

### ISSUE THREAD

**Issue by TactfulBean** [1111mp/nvm-desktop#12]
现在程序的默认安装路径在C盘，node的默认安装路径也在c盘，能否自定义更改程序的安装位置以及在程序内部更改node的安装路径？

**Comment by 1111mp** [comment]
后续我会支持`nvm-desktop`自定义选择安装路径的功能，但是`node`的安装路径的自定义功能就不会跟进了，主要是如果允许自定义`node`的安装路径的话：

那么在`nvmd`中每次寻找正确的`node`版本的话都需要把每个目录都检索一遍（并且为了更好的体验，需要保存历史设置过的目录路径，然后每个目录都要检索），这样的话对性能也有影响；

而且也担心如果安装在非c盘目录，`windows`系统容易出现权限问题（不同的计算机会有不同的表现，不容易排查）。

所以希望理解。

**Comment by XiaoMo-Donald** [comment]
但是我的C盘已经爆炸了，非常不想安装在C盘怎么办

**Comment by 1111mp** [comment]
@XiaoMo-Donald 能理解 所以在directory分支已经实现了程序以及nodejs的自定义路径的功能了，但是`nvmd-command`可能还存在未知的问题 [#17](https://github.com/1111mp/nvm-desktop/issues/17)，所以想等到确认解决之后再一起发到下一个版本上去。望理解。 如果比较急的话可以按照文档自己编译生产包的。谢谢

**Comment by XiaoMo-Donald** [comment]
@1111mp 不着急不着急，期待发版 现在在用nvm管理，但是有时候一次性需要打开不同的项目（需要不同的node版本）所以觉得有点麻烦，刚好这边有这个可以给项目配置单独的node版本的功能，就比较期待了

**Comment by 1111mp** [comment]
好的好的 问题解决之后会第一时间发出来的 谢谢

**Comment by 1111mp** [comment]
已在 [Release v2.5.0](https://github.com/1111mp/nvm-desktop/releases/tag/v2.5.0) 中实现。
如果有问题请随时打开此问题。
