### ISSUE TITLE
[BUG]列表中版本的状态判断错误

### ISSUE THREAD

**Issue by Chosenooo** [1111mp/nvm-desktop#121]
如下图，实际只安装了一个版本，但是显示多个版本安装。
状态判断可能是startWith 或者 contains 。
软件版本：4.0.0
![image](https://github.com/user-attachments/assets/c04bb90c-7a5b-4adc-9e82-b51bf5483574)

**Comment by 1111mp** [comment]
确实是因为使用了 includes 方法来判断造成了这个问题 我会在下个版本中修复这个问题 非常感谢你提出来这个问题 谢谢 🌹

**Comment by 1111mp** [comment]
最新的 [Release 4.0.1](https://github.com/1111mp/nvm-desktop/releases/tag/v4.0.1) 版本已经修复了这个问题 那么这个issue我就先关闭了 当然后续如果有任何问题都可以随时打开 谢谢
