### ISSUE TITLE
[BUG]打开之后，界面就跟卡死了一样，什么也无法点击

### ISSUE THREAD

**Issue by a1643977841** [1111mp/nvm-desktop#124]
**Describe the bug**

**To Reproduce**
直接打开软件

**Expected behavior**

**Screenshots**
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/8ef85ad6-d0b5-4433-94e1-60110750b450">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS15
 - Arch: [e.g. arm64] arm64
 - Version [e.g. 4.0.0] 4.0.0

**Additional context**

---

**描述错误**
清晰简明地描述错误是什么。

**重现步骤**
重现该行为的步骤：
1. 进入 '...'
2. 点击 '....'
3. 向下滚动到 '....'
4. 看到错误

**预期行为**
清晰简明地描述你期望发生的事情。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**桌面设备（请填写以下信息）：**
 - 操作系统: [例如 macOS]
 - 架构: [例如 arm64]
 - 版本: [例如 4.0.0]

**附加上下文**
在此添加有关问题的任何其他上下文。

**Comment by 1111mp** [comment]
首先请确保你下载的安装包是正确的：
![image](https://github.com/user-attachments/assets/db48b00d-59ef-42ab-8044-69d632554379)

根据提供的信息，你的设备是 `apple arm64` 架构 所以应该下载[NVM.Desktop_4.0.0_aarch64.dmg](https://github.com/1111mp/nvm-desktop/releases/download/v4.0.0/NVM.Desktop_4.0.0_aarch64.dmg)

如果下载的安装包是正确的话 也有可能和这个问题有关：https://github.com/tauri-apps/tauri/issues/11308

我一会儿发布一个 alpha 版本出来 会提供 打开开发者工具的功能 到时候如果有时间的话 下载安装验证一下是否还会有这个问题（打开开发者工具 看是否有报错）

**Comment by a1643977841** [comment]
> 首先请确保你下载的安装包是正确的： ![image](https://private-user-images.githubusercontent.com/31227919/374844213-db48b00d-59ef-42ab-8044-69d632554379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTE0MzUsIm5iZiI6MTcyODYxMTEzNSwicGF0aCI6Ii8zMTIyNzkxOS8zNzQ4NDQyMTMtZGI0OGIwMGQtNTllZi00MmFiLTgwNDQtNjlkNjMyNTU0Mzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAxNDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYzBlY2JmMTI3N2ExNGY1ODMwODRjZmIyZTM2ZTVkYmU2Y2MyZDNhZDc0YzBjYWRlZWJhMWZhOTAzNDExNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-Kxw-b8KOtYzFr3toHkRhANAfLUvGa1rsfqZ-NCq9Qs)
> 
> 根据提供的信息，你的设备是 `apple arm64` 架构 所以应该下载[NVM.Desktop_4.0.0_aarch64.dmg](https://github.com/1111mp/nvm-desktop/releases/download/v4.0.0/NVM.Desktop_4.0.0_aarch64.dmg)
> 
> 如果下载的安装包是正确的话 也有可能和这个问题有关：[tauri-apps/tauri#11308](https://github.com/tauri-apps/tauri/issues/11308)
> 
> 我一会儿发布一个 alpha 版本出来 会提供 打开开发者工具的功能 到时候如果有时间的话 下载安装验证一下是否还会有这个问题（打开开发者工具 看是否有报错）

我确保我下载的版本是正确的。
<img width="941" alt="image" src="https://github.com/user-attachments/assets/3d8d82a6-5a06-4689-b103-b1b2a25352d6">

**Comment by 1111mp** [comment]
alpha版本已经发出来了 可以下载安装一下试试呢 https://github.com/1111mp/nvm-desktop/releases/tag/alpha

**Comment by a1643977841** [comment]
> alpha版本已经发出来了 可以下载安装一下试试呢 https://github.com/1111mp/nvm-desktop/releases/tag/alpha
已经更新为此版本，但还是如之前描述，任何按钮都无法点击
<img width="1350" alt="image" src="https://github.com/user-attachments/assets/b3087c42-b167-4adc-980e-2480462c2982">

**Comment by 1111mp** [comment]
你在右上角菜单里面点击 Open Dev Tools 打开开发者工具 看一下是否有报错呢

**Comment by a1643977841** [comment]
> 你在右上角菜单里面点击 Open Dev Tools 打开开发者工具 看一下是否有报错呢

我没有找到Open Dev Tools，请问可以指引一下吗

**Comment by a1643977841** [comment]
> 你在右上角菜单里面点击 Open Dev Tools 打开开发者工具 看一下是否有报错呢

如图
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/a7a6ce13-b17e-44e7-b9b4-26054bcea1a1">

**Comment by 1111mp** [comment]
在桌面顶部的菜单栏，会有nvm-desktop的一个托盘菜单，点击打开菜单选项中会有这个选项

**Comment by a1643977841** [comment]
> 在桌面顶部的菜单栏，会有nvm-desktop的一个托盘菜单，点击打开菜单选项中会有这个选项

已发图

**Comment by 1111mp** [comment]
ok 那应该清楚是什么问题造成的了（`Content Security Policy` 安全策略导致的） 后面我更新一下`csp`的配置 谢谢耐心提供相关的信息 🌹

**Comment by a1643977841** [comment]
> ok 那应该清楚是什么问题造成的了（`Content Security Policy` 安全策略导致的） 后面我更新一下`csp`的配置 谢谢耐心提供相关的信息 🌹

这个和系统版本有关系吗，是因为macOS15的原因吗

**Comment by 1111mp** [comment]
> 这个和系统版本有关系吗，是因为macOS15的原因吗

没关系 是html的内容加载安全策略的限制 不允许 `ipc`这个协议 需要更改一下对应的 `csp`  配置即可

我重新打包 稍后麻烦你这边再去 https://github.com/1111mp/nvm-desktop/releases/tag/alpha 地址下重新下载安装一下 麻烦你了 谢谢

**Comment by a1643977841** [comment]
> > 这个和系统版本有关系吗，是因为macOS15的原因吗
> 
> 没关系 是html的内容加载安全策略的限制 不允许 `ipc`这个协议 需要更改一下对应的 `csp` 配置即可

大概什么时候可以修复呢

**Comment by 1111mp** [comment]
代码已经修复了 在重新打包 打包好了 我告诉你
也可以在这里查看打包进度 https://github.com/1111mp/nvm-desktop/actions/runs/11285934200

**Comment by 1111mp** [comment]
虽然任务还没结束 但是可以下载了
![image](https://github.com/user-attachments/assets/09a47c47-bfa1-4339-b73f-14f56d1b7405)

**Comment by a1643977841** [comment]
好的 发件人: ***@***.*** ***@***.***> 代表 The1111mp ***@***.***>日期: 星期五, 2024年10月11日 11:42收件人: nvm-desktop ***@***.***>抄送: 1643977841 ***@***.***>, author ***@***.***>主题: Re: [1111mp/nvm-desktop] [BUG]打开之后，界面就跟卡死了一样，什么也无法点击 (Issue #124)代码已经修复了 在重新打包 打包好了 我告诉你—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by a1643977841** [comment]
> 虽然任务还没结束 但是可以下载了 ![image](https://private-user-images.githubusercontent.com/31227919/375618842-09a47c47-bfa1-4339-b73f-14f56d1b7405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mjg2NTYsIm5iZiI6MTcyODYyODM1NiwicGF0aCI6Ii8zMTIyNzkxOS8zNzU2MTg4NDItMDlhNDdjNDctYmZhMS00MzM5LWI3M2YtMTRmNTZkMWI3NDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA2MzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNjE5YWQ2YTBiNWJkNGU3ZDkwMjRlMTI3Njk0NWYzZDQwMmQ3ZmMxYjJmYTJiYjQ0ZDlmNjhmMzkyN2IzMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.54_mElX-dHAYdnEIZkg4C3nZCjxUpNzj1ZTicxzg-x0)

我已下载最新修复的版本，已解决开发者工具里面的报错，但似乎并没有解决无法点击的问题。现在还是一如以往，无法点击任何按钮。

<img width="1059" alt="image" src="https://github.com/user-attachments/assets/38519f05-8b32-4a79-9e43-852af2913894">

**Comment by 1111mp** [comment]
可以提供一下日志文件吗 在 `/Library/Logs/io.github.1111mp.nvm-desktop` 目录下

**Comment by a1643977841** [comment]
> 可以提供一下日志文件吗 在 `/Library/Logs/io.github.1111mp.nvm-desktop` 目录下

确定是在这个目录吗，我的电脑里面并没有发现此目录

**Comment by 1111mp** [comment]
`"/Library/Logs/"` 目录下找一下呢
![image](https://github.com/user-attachments/assets/785d8a3c-2c76-41f9-bf3d-4308066cff61)

**Comment by a1643977841** [comment]
你想说的是~/Library/Logs/吧，我找到了相关日志
[Uploading NVM Desktop.log…]()

**Comment by a1643977841** [comment]
[NVM Desktop.log](https://github.com/user-attachments/files/17339247/NVM.Desktop.log)

**Comment by 1111mp** [comment]
目录 `"$HOME/.nvmd"` 在你系统中存在吗 可以贴出该目录下的文件吗（截图）

**Comment by a1643977841** [comment]
<img width="481" alt="image" src="https://github.com/user-attachments/assets/a16da076-f460-40e4-8ddf-a474f4df22a4">

**Comment by 1111mp** [comment]
这个问题很奇怪 可能是因为macos15 也有可能是tauri的问题：https://github.com/tauri-apps/tauri/issues/11254

我使用 macos 15 系统重新编译打包了 麻烦你这边有时间再下载安装试试呢
![image](https://github.com/user-attachments/assets/0ec64105-0b58-4ffb-8dfc-727fa716717d)

**Comment by a1643977841** [comment]
我已下载你刚刚打包的版本但日志中还是有如下错误
[2024-10-11][08:04:38][app][ERROR] file not found "/Users/ahao/.nvmd/setting.json"
[2024-10-11][08:04:38][app][ERROR] failed to read the file "/Users/ahao/.nvmd/default"
[2024-10-11][08:04:38][app][ERROR] file not found "/Users/ahao/.nvmd/versions.json"
[2024-10-11][08:04:38][app][ERROR] file not found "/Users/ahao/.nvmd/groups.json"
[2024-10-11][08:04:38][app][ERROR] file not found "/Users/ahao/.nvmd/projects.json"

**Comment by 1111mp** [comment]
这些错误不会影响程序的运行 代码对其都做了捕获处理的 未找到这些文件就会给默认值
![image](https://github.com/user-attachments/assets/38456c5a-14c0-4eeb-9b99-24966430c66b)

现在还是一样有问题吗

**Comment by a1643977841** [comment]
是的现在还是一样的问题，界面什么都无法点击，你如果方便可以远程我的电脑进一步查看

**Comment by 1111mp** [comment]
很奇怪 我把tauri的版本升级一下 然后重新打包 一会儿你再试试 

我自己也是m1 max 芯片的 运行没遇到这个问题 也升级到最新的系统了 就很奇怪 可能是tauri的问题 需要持续跟踪一下 如果你要是用的话 可以使用 3.4.0版本 这是 electron的版本 应该没这个问题

**Comment by a1643977841** [comment]
> 很奇怪 我把tauri的版本升级一下 然后重新打包 一会儿你再试试
> 
> 我自己也是m1 max 芯片的 运行没遇到这个问题 也升级到最新的系统了 就很奇怪 可能是tauri的问题 需要持续跟踪一下 如果你要是用的话 可以使用 3.4.0版本 这是 electron的版本 应该没这个问题

**Comment by a1643977841** [comment]
我暂时不急使用，等待你的修复包完成。
我不小心点击了关闭，能否帮忙重新打开一下。

**Comment by 1111mp** [comment]
alpha 的安装包已经更新了 麻烦再验证一下呢 如果还是不行 我去tauri下面开个issue 追踪确认一下这个问题

**Comment by a1643977841** [comment]
我已经重新下载alpha的安装包，并进行了验证，还是之前的问题

**Comment by 1111mp** [comment]
好的 谢谢反馈 🌹

**Comment by 1111mp** [comment]
刚刚看了一下 electron 的相关问题 不太清楚是否也和 macos15 有关：https://github.com/electron/electron/issues/43995

后面有解决方案之后我这边第一时间反馈给你

**Comment by a1643977841** [comment]
好的

**Comment by 1111mp** [comment]
macOS 15版本貌似确实存在很多问题：https://www.reddit.com/r/MacOS/comments/1fihlge/macos_15_sequoia_bugs_and_issues_megathread/

我目前是 15.0.1 版本

**Comment by a1643977841** [comment]
或许等下一次更新就修复了

**Comment by a1643977841** [comment]
hello，我最近首次打开nvm-desktop，发现界面可以点击能使用了

**Comment by 1111mp** [comment]
现在所有功能都能正常使用吗 (系统有更新吗 还是之前安装的版本吗)

或许和 `tauri` 的这里有关：[#11355](https://github.com/tauri-apps/tauri/pull/11355)

**Comment by a1643977841** [comment]
我没有做任何操作，只是当初和你沟通完之后直到今天我才重新打开，突然就可以用了。

**Comment by 1111mp** [comment]
那就很奇怪了 电脑重启了吗 

如果能用的话 你先试试各个功能 如果有什么问题随时留言反馈

**Comment by ppizzadog** [comment]
> 那就很奇怪了 电脑重启了吗
> 
> 如果能用的话 你先试试各个功能 如果有什么问题随时留言反馈

你好，我遇到相同问题，运行在 apple M+macos15

**Comment by 1111mp** [comment]
@ppizzadog 能提供一下运行日志吗 还有目前在用的是什么版本

**Comment by ppizzadog** [comment]
[NVM.Desktop.log](https://github.com/user-attachments/files/17614328/NVM.Desktop.log)

版本是NVM.Desktop_4.0.2_aarch64 
@1111mp

**Comment by 1111mp** [comment]
@ppizzadog 你试试通过终端启动呢 前面加个 `sudo` 然后截屏看一下有没有报错

或者提供一下系统的自带的日志：

1. 使用Console应用程序：
打开Finder，进入“应用程序”>“实用工具”，然后双击“Console”应用程序。
在左侧栏，你可以选择“系统日志”或“用户日志”来查看不同类型的日志。
使用搜索框输入你的应用程序名称或相关关键词以筛选日志。

2. 命令行工具：
你可以使用命令行工具log来查看日志。打开终端并运行：
```bash
log show --predicate 'process == "YourAppName"' --info
```
这个命令将显示应用程序的历史日志。你可以根据需求修改--info、时间范围等参数。

**Comment by ppizzadog** [comment]
![WeChate8f5581b762a8e85ce1c638d9253fe0a](https://github.com/user-attachments/assets/c7984dff-5ff5-44a9-be44-66b5f80e9c8a)
[NVM Desktop.log](https://github.com/user-attachments/files/17614495/NVM.Desktop.log)

@1111mp

**Comment by 1111mp** [comment]
> 或者提供一下系统的自带的日志：
>
>使用Console应用程序：
打开Finder，进入“应用程序”>“实用工具”，然后双击“Console”应用程序。
在左侧栏，你可以选择“系统日志”或“用户日志”来查看不同类型的日志。
使用搜索框输入你的应用程序名称或相关关键词以筛选日志。


@ppizzadog 能提供一下操作系统的日志吗 目前通过程序中收集上来的日志看不出啥问题 不好排查 

对了 顶部菜单栏里面的托盘菜单能够正常交互吗

**Comment by 1111mp** [comment]
@ppizzadog 有时间的话，下载试用最新的alpha版本看看还会这样吗 https://github.com/1111mp/nvm-desktop/releases/tag/alpha

**Comment by xiaopengmvp520** [comment]
> @ppizzadog 有时间的话，下载试用最新的alpha版本看看还会这样吗 https://github.com/1111mp/nvm-desktop/releases/tag/alpha

我刚刚下载了链接的最新版本，我是升级了 macos15的最新系统，i9的芯片，还是和楼上一样的状况，打开页面后，卡死了一样，点击页面都没反应

**Comment by 1111mp** [comment]
@xiaopengmvp520 能提供一下日志吗，最好是上面说的系统的运行日志。然后顶部系统菜单交互正常吗。
目前来说根据应用自己收集上来的日志看不出什么问题，我本地也不能复现，如果有时间的话试试按照readme里的教程把代码克隆到本地运行一下试试呢，看会不会有额外的报错信息……比如死锁这种情况……我自己本地也会尽量找一些设备测试一下，抱歉啊

**Comment by 1111mp** [comment]
@xiaopengmvp520 @ppizzadog @a1643977841  这个问题应该是解决了 最终定位下来不是tauri的问题 而是intro.js造成的 蒙层占据全屏导致无法交互 等待alpha编译结束 可以下载安装 看是否还会复现这个问题 谢谢

**Comment by ppizzadog** [comment]
@1111mp 可以使用 谢谢

**Comment by a1643977841** [comment]
@1111mp 破案了吗，哈哈，真好

**Comment by mimimiaomiao1** [comment]
> @xiaopengmvp520 @ppizzadog @a1643977841 这个问题应该是解决了 最终定位下来不是tauri的问题 而是intro.js造成的 蒙层占据全屏导致无法交互 等待alpha编译结束 可以下载安装 看是否还会复现这个问题 谢谢

请问我应该下载哪个版本来使用呢?

**Comment by 1111mp** [comment]
目前最新的 [release v4.0.3](https://github.com/1111mp/nvm-desktop/releases/tag/v4.0.3) 版本已经发布，这个问题应该得到了解决，那么我就先把这个问题关闭了，当然后续如果还有问题请随时打开。
