### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by clx20000410** [1111mp/nvm-desktop#125]
**描述错误**
正常安装成功后安装node报错

**重现步骤**
选择一个版本点击下载node进度调加载到一半后有错误提示

**预期行为**
安装node成功

**截图**
![企业微信截图_17286104395960](https://github.com/user-attachments/assets/bc7c53f6-d8c8-4cfb-b69d-29771d051dec)

**桌面设备（请填写以下信息）：**
 - 操作系统: windows 10
 - 架构: x64
 - 版本: 4.0.0
**附加上下文**
NVM.Desktop_4.0.0_x64-setup.exe   安装的是这个

**Comment by 1111mp** [comment]
设置里面换个镜像地址再试试呢 这个可能是因为下载一半然后中断了

**Comment by clx20000410** [comment]
内置两个镜像地址我试了都不可以呢

**Comment by clx20000410** [comment]
这是网络问题对吗

**Comment by 1111mp** [comment]
试试这个地址呢https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/

**Comment by clx20000410** [comment]
可以安装了, 但是现在
![image](https://github.com/user-attachments/assets/3026ee6b-8c9f-4135-a9a3-29aaa68a8e63)
这是为什么

**Comment by clx20000410** [comment]
![image](https://github.com/user-attachments/assets/b0c6abaf-f253-471b-81c3-e302e6ec0e79)
我现在又这个环境变量呀

**Comment by 1111mp** [comment]
重启一下 powershell 呢 然后执行 `nvmd --help` 看是否正常 `node -v`可以吗 （客户端里面下载之后是否通过 `应用` 按钮将该版本设置为全局默认的版本）
可以看看 `"%HOMEPATH%\.nvmd\bin"` 目录下是否存在 `npm.exe` 和 `npm.cmd` 文件
如果都没问题 那使用cmd终端来运行

**Comment by 1111mp** [comment]
这个问题很久没有反馈，通过文档应该能够解决，我先关闭此问题。后续有问题可以随时重新开启。谢谢。
