### ISSUE TITLE
[BUG] 选择v22.3.0的node的版本的时候，控制台输入会报错command not found，而其他的版本的node可以

### ISSUE THREAD

**Issue by DylanChen08** [1111mp/nvm-desktop#127]
**Describe the bug**
选择v22.3.0的node的版本的时候，控制台输入会报错command not found

**To Reproduce**
1. Open the software
2. Select node version v22.3.0
3. Install any dependencies, here is an example of installing pnpm
4. Report an error command not found
5. Switch to another node version, such as v22.2.0
6. Install pnpm again, installation is successful

**Expected behavior**
Expect v22.3.0 pnpm to install successfully

**Screenshots**
v22.3.0 安装依赖失败
![v22.3.0安装失败](https://github.com/user-attachments/assets/06214cdb-3738-4d0a-a8bb-f070bf7f0ffe)

v22.2.0 安装依赖成功
![22.2.0](https://github.com/user-attachments/assets/d5595b60-6016-4e25-b8e2-6d28584c7107)

**Desktop (please complete the following information):**
 - OS: [windows 11  专业版]
 - Arch: [x64-based PC]
 - Version [22631.4317]

**Additional context**

---

**描述错误**
清晰简明地描述错误是什么。

**重现步骤**
重现该行为的步骤：
1. 打开软件
2. 选择node版本v22.3.0
3. 安装任意的依赖，这里示例安装pnpm
4. 报错command not found 
5. 切换其他node版本，如切换v22.2.0
6. 再次安装pnpm，安装成功

**预期行为**
清晰简明地描述你期望发生的事情。

**截图**
v22.3.0 安装依赖失败
![v22.3.0安装失败](https://github.com/user-attachments/assets/06214cdb-3738-4d0a-a8bb-f070bf7f0ffe)

v22.2.0 安装依赖成功
![22.2.0](https://github.com/user-attachments/assets/d5595b60-6016-4e25-b8e2-6d28584c7107)

**桌面设备（请填写以下信息）：**
 - 操作系统: [windows 11  Professional]
 - 架构: [例如 arm64]
 - 版本: [例如 4.0.0]

**附加上下文**
在此添加有关问题的任何其他上下文。

**Comment by 1111mp** [comment]
你可以查看一下在 `%HOMEPATH%\.nvmd\bin` 目录下是否存在 `npm.exe` & `npm.cmd` 
然后确认一下`%HOMEPATH%\.nvmd\versions\22.3.0` 目录下 文件是否都存在，比如这些：
<img width="785" alt="Screenshot 2024-10-12 at 09 54 24" src="https://github.com/user-attachments/assets/241a97cd-d606-4863-be20-48cdd8b69b2b">

可以尝试卸载 22.3.0 版本然后再安装一下试试 

或者直接去 `%HOMEPATH%\.nvmd\versions\22.3.0` 目录下执行 `npm -v` `node -v` 看命令是否正常

**Comment by DylanChen08** [comment]
谢谢，重新安装已经解决
