### ISSUE TITLE
[FEATURE]建议增加 nvmd install &  nvmd set registry 命令

### ISSUE THREAD

**Issue by zhuyuanmin** [1111mp/nvm-desktop#134]
建议
1. 增加 nvmd install version 命令
2. 增加 nvmd set registry http://xxx 命令

**Comment by 1111mp** [comment]
这个功能我也一直在考虑需不需要实现，但是感觉又和`nvm-desktop`的初衷有些出入（通过可视化界面操作来管理node版本），如果实现了这个功能的话其实就完全没必要使用可视化的客户端了，直接使用cli命令行工具就行了
