### ISSUE TITLE
[FEATURE] 建议项目增加一个直接打开vscode

### ISSUE THREAD

**Issue by zengxj0v0** [1111mp/nvm-desktop#135]

**Comment by 1111mp** [comment]
可以的 这个功能我会在下个版本中实现 🌹

**Comment by 1111mp** [comment]
目前最新的 [release v4.0.3](https://github.com/1111mp/nvm-desktop/releases/tag/v4.0.3) 版本已经发布，这个功能已经实现，那么我就先把这个问题关闭了，当然后续如果还有问题请随时打开。
