### ISSUE TITLE
[BUG]windows11 项目添加后无法移除

### ISSUE THREAD

**Issue by journeybyte** [1111mp/nvm-desktop#136]
**Expected behavior**
**描述错误**
清晰简明地描述错误是什么。

**重现步骤**
重现该行为的步骤：
1. 打开软件
2. 点击添加项目
3. 点击移除=>确认
4. 窗口隐藏 但所选项目未被移除

**预期行为**
希望能项目正常移除

**截图**
![recording](https://github.com/user-attachments/assets/afaef22b-2052-4407-8f6f-5c1317607939)

**桌面设备（请填写以下信息）：**
 - 操作系统: windows11 23H2
 - 架构: i9-13900HX 
 - 版本: 4.0.2

**Comment by 1111mp** [comment]
是的 这个问题我自己也遇到了 已经在昨天修复了 [commit 72b3617](https://github.com/1111mp/nvm-desktop/commit/72b3617784e0776be2324c1fc9a91497b109915b) 下个版本会修复这个问题 谢谢

目前的解决方法就是选中一个版本之后再移除

**Comment by journeybyte** [comment]
> 是的 这个问题我自己也遇到了 已经在昨天修复了 [commit 72b3617](https://github.com/1111mp/nvm-desktop/commit/72b3617784e0776be2324c1fc9a91497b109915b) 下个版本会修复这个问题 谢谢
> 
> 目前的解决方法就是选中一个版本之后再移除

好的，感谢回答~选中一个版本后确实可以删除。
