### ISSUE TITLE
[BUG]Ubuntu 22.04桌面版安装后没有快捷方式

### ISSUE THREAD

**Issue by ZimaBlueee** [1111mp/nvm-desktop#137]
步骤：
1. 下载NVM.Desktop_4.0.2_amd64.deb
2. sudo apt install ./NVM.Desktop_4.0.2_amd64.deb

全程无报错，但是从应用里找不到该软件，不知道从哪里打开

**Comment by 1111mp** [comment]
这个问题在最近一次提交中已经修复了 我会先编译 alpha 版本出来 麻烦你有时间下载安装验证一下 下载地址：https://github.com/1111mp/nvm-desktop/releases/tag/alpha

> 下载之前请确保 https://github.com/1111mp/nvm-desktop/actions/runs/11650222253 这个编译任务已完成

之前是因为 `/usr/share/applications/NVM\ Desktop.desktop`配置文件错误造成的 建议安装新版本之前 先手动将`/usr/share/applications/NVM\ Desktop.desktop`文件删除 然后执行安装包这时候才会正常显示卸载按钮 先卸载之前的版本 然后安装alpha版本 谢谢

> linux现在已经编译好了

**Comment by 1111mp** [comment]
目前最新的 [release v4.0.3](https://github.com/1111mp/nvm-desktop/releases/tag/v4.0.3) 版本已经发布，这个问题应该得到了解决，那么我就先把这个问题关闭了，当然后续如果还有问题请随时打开。
