### ISSUE TITLE
[FEATURE]每次更新过后，yarn、npm等相关命令zsh: permission denied

### ISSUE THREAD

**Issue by zwtderek1986** [1111mp/nvm-desktop#138]
每次更新后，都需要重新赋予权限比较麻烦，期望优化一下

**Comment by 1111mp** [comment]
可以的，这个问题也一直在考虑，初步的方案是每次升级完成之后弹出一个弹出框（需要管理员用户密码）然后执行命令去赋予权限，或者你有什么更好的想法……

**Comment by zwtderek1986** [comment]
如果没发自动赋予权限的话，也没什么更好的想法，自动弹出或者加个按钮一键赋权都行

**Comment by 1111mp** [comment]
因为`nvmd`可执行文件没有证书进行签名，苹果的安全策略会阻止分配权限，完美的解决方案当然是用证书对文件进行签名，但是涉及到苹果开发者账号（付费）。是的现在应该只能在升级过后打开界面的时候弹框让输入密码赋予一下权限，加个按钮让用户自己手动赋值也可以。

不过在此之前 我先测试一下在打包的时候（打包平台）对`nvmd`进行一下权限修改（`chmod +x nvmd`） 看权限是否会保留

**Comment by 1111mp** [comment]
@zwtderek1986 我已经在打包界面添加了chmod赋予权限 有时间能帮忙测试一下吗 https://github.com/1111mp/nvm-desktop/releases/tag/alpha 下载最新的安装包安装一下 不过在启动之前需要把 `$HOME/.nvmd/migration` 文件删掉 然后启动 这样就会触发migrate脚本 这时候再试试还会有这个问题吗  谢谢 🌹 

晚点时候我也会测试一下的

**Comment by 1111mp** [comment]
> 不过在此之前 我先测试一下在打包的时候（打包平台）对nvmd进行一下权限修改（chmod +x nvmd） 看权限是否会保留

@zwtderek1986 测试过了 这种方式可行 从下个版本开始应该就不会出现这个问题了 谢谢

**Comment by zwtderek1986** [comment]
> @zwtderek1986 我已经在打包界面添加了chmod赋予权限 有时间能帮忙测试一下吗 https://github.com/1111mp/nvm-desktop/releases/tag/alpha 下载最新的安装包安装一下 不过在启动之前需要把 `$HOME/.nvmd/migration` 文件删掉 然后启动 这样就会触发migrate脚本 这时候再试试还会有这个问题吗 谢谢 🌹
> 
> 晚点时候我也会测试一下的

不好意思，昨天有事，才看见！谢谢

**Comment by 1111mp** [comment]
没关系 我在自己的设备上已经测试过了 方案可行

目前最新的 [release v4.0.3](https://github.com/1111mp/nvm-desktop/releases/tag/v4.0.3) 版本已经发布，这个问题应该得到了解决，那么我就先把这个问题关闭了，当然后续如果还有问题请随时打开。

**Comment by zwtderek1986** [comment]
更新后
<img width="298" alt="image" src="https://github.com/user-attachments/assets/7f929df8-e2b7-4be0-96a8-b8de21e54b0c">
