### ISSUE TITLE
[BUG] 全局安装@vue/cli 出现nvm-desktop: command not found: "vue"，如何解决

### ISSUE THREAD

**Issue by carpONE** [1111mp/nvm-desktop#139]
**Describe the bug**
Global installation @vue/cli appears nvm-desktop: command not found: "vue", how to solve? 

**Screenshots**
![image](https://github.com/user-attachments/assets/458e0fb0-8994-4702-809b-fe3f86fa1171)

**Desktop (please complete the following information):**
 - OS: [e.g. windows10]
 - Arch: X64
 - Version 4.0.3

**Additional context**
Installed in the node installation directory, now how to set the root of npm to the global node version set by nvm? 

---

**描述错误**
全局安装@vue/cli 出现nvm-desktop: command not found: "vue"，如何解决？

**截图**
![image](https://github.com/user-attachments/assets/458e0fb0-8994-4702-809b-fe3f86fa1171)

**桌面设备（请填写以下信息）：**
 - 操作系统: windows10
 - 架构: x64
 - 版本: 4.0.3

**附加上下文**
安装在了node安装目录下，现在如何设置为npm 的root为nvm所设置的全局node版本下？

**Comment by 1111mp** [comment]
参考这里 https://github.com/1111mp/nvm-desktop/issues/23

**Comment by carpONE** [comment]
我设置了系统变量，是不是去掉就可以了？
![image](https://github.com/user-attachments/assets/e0428cdc-8036-4fb8-8728-15c1e87e812c)

**Comment by 1111mp** [comment]
这个应该是重复的问题 并且可以通过文档解决 那么就先关闭这个问题了
