### ISSUE TITLE
识别不到本地已经安装过的node

### ISSUE THREAD

**Issue by zhoumowan** [1111mp/nvm-desktop#140]
在安装nvmd以后不能直接识别到本地已经存在的node版本吗？需要什么配置吗

**Comment by 1111mp** [comment]
默认是需要在主界面下载的 不过设置里面可以更改node的下载目录 不过node的目录是以版本号为文件目录名称的 比如：
![image](https://github.com/user-attachments/assets/8f7cfddc-bb18-44da-88c8-11135441ce99)

**Comment by 1111mp** [comment]
这个问题应该可以通过文档解决 那么就先关闭了 谢谢
