### ISSUE TITLE
[FEATURE]可不可以在打开vscode后关闭命令窗口

### ISSUE THREAD

**Issue by shallow-dreamer** [1111mp/nvm-desktop#142]
![image](https://github.com/user-attachments/assets/a496d6b5-4981-4f30-85d5-096b0f233ea3)
打开项目后cmd窗口不会关闭，打开多个时后面启动的cmd会关  ?_?

**Comment by 1111mp** [comment]
我的电脑会在vscode打开之后会自动关闭cmd终端 你试试在设置里面改一下设置 把`code.cmd`换成完整的`code.exe`路径试试呢

**Comment by shallow-dreamer** [comment]
nice
