### ISSUE TITLE
为啥切换版本后就会找不到yarn

### ISSUE THREAD

**Issue by kbjing** [1111mp/nvm-desktop#144]
nvm-desktop: command not found: "yarn"

您好，可以解答一下这个问题吗
现在除了一开始选择的16版本的node，切换到别的版本，就会报这个错误

**Comment by 1111mp** [comment]
每个node版本之间都是独立隔离开的 比如你在16版本的node下使用npm全局安装了一些包 切到另一个node版本 那么就需要重新全局安装了 如果需要切换版本之后还要生效的话 可以通过`npm config set prefix "/path/to/folder"`更改npm全局安装包的目录（需要将这个目录添加到系统环境变量 要不然系统不能识别到） 这样每个node版本就都能用了
