### ISSUE TITLE
全局安装 pnpm 后提示 nvm-desktop: command not found: "pnpm"

### ISSUE THREAD

**Issue by clx20000410** [1111mp/nvm-desktop#145]
[BUG]全局安装 pnpm 后提示 nvm-desktop: command not found: "pnpm"
nvmd版本：4.0.4 
os版本： win11

![image](https://github.com/user-attachments/assets/6fbf41f8-58d7-47cd-93be-a2684bfcb260)

**Comment by 1111mp** [comment]
查看这里看是否能解决问题：https://github.com/1111mp/nvm-desktop/issues/23

**Comment by 1111mp** [comment]
这个问题可以通过文档解决 那么就先关闭这个问题了
