### ISSUE TITLE
[BUG]downloading error

### ISSUE THREAD

**Issue by Y843512864** [1111mp/nvm-desktop#146]
![1](https://github.com/user-attachments/assets/64234eb7-634c-4197-bcd6-fce5cd269872)

**Comment by 1111mp** [comment]
查看这里的文档：https://github.com/1111mp/nvm-desktop/issues/126

> 跟[#125](https://github.com/1111mp/nvm-desktop/issues/125)重复

**Comment by 1111mp** [comment]
这个问题和 #125 重复 可以通过文档解决 那么就先关闭这个问题了
