### ISSUE TITLE
[BUG] 每次打开软件界面都缩小

### ISSUE THREAD

**Issue by github-sunpiaoliang** [1111mp/nvm-desktop#147]
**描述错误**
每次打开软件界面都小一点

**重现步骤**
重现该行为的步骤：
1. 打开软件
2. 关闭软件
3. 打开 软件
4. 看到错误

**预期行为**
只想正常看到界面目前已经缩小到很小了  差不多4次左右 已经不能操作了 

**截图**
![image](https://github.com/user-attachments/assets/756f8f91-26f6-4417-8eef-8e1c3370c81b)

**桌面设备（请填写以下信息）：**
 - 操作系统:  macos
 - 架构: arm64
 - 版本: 15.1.1

**Comment by 1111mp** [comment]
我感觉这个应该是和插件 [tauri-plugin-window-state](https://tauri.app/plugin/window-state/) 有关 该插件是用来在应用退出时保存位置尺寸等信息，下次打开还原位置和尺寸。不过这个问题还是第一次遇到。你这边是使用的外接显示屏吗（2k或者4k？） 试试重启一下电脑 看还会复现吗
该插件保存这些信息的文件在这个目录下：`/Library/Application Support/io.github.1111mp.nvm-desktop/.window-state.json` 你可以查看一下里面的内容 或者直接删除也行 然后重启一下试试

> 更新

不过我后面会设置一下应用的最小尺寸 来尽量避免这个问题吧

**Comment by 1111mp** [comment]
已经发布了一个 [Alpha](https://github.com/1111mp/nvm-desktop/releases/tag/alpha) 版本 你可以下载试试能不能解决

**Comment by github-sunpiaoliang** [comment]
好的 谢谢。
删除这个是能解决问题的 /Library/Application Support/io.github.1111mp.nvm-desktop/.window-state.json
我是在 外接屏幕上出现的问题 ， 在原始屏幕上 没有问题。
