### ISSUE TITLE
[BUG]为什么npm任何操作都提示这个，执行npm update follow ，npm这个命令就直接失效了

### ISSUE THREAD

**Issue by AAaNEIgeiDEItao** [1111mp/nvm-desktop#148]
<img width="454" alt="image" src="https://github.com/user-attachments/assets/67c3ec4e-b673-48ea-a02b-5b3bcc36d1ff" />

**Comment by 1111mp** [comment]
这是是你安装的包 follow 的警告 node版本不符合其要求

npm update follow会根据规则将follow更新到最新版本，但是 package.json 文件中的版本并不会更新；但是 node_modules 目录下安装的版本是最新的，你可以检查一下； nvmd并没有改变其默认行为，可查看文档：https://docs.npmjs.com/cli/v9/commands/npm-update

**Comment by 1111mp** [comment]
这个问题可以通过文档解决 那么就先关闭这个问题了
