### ISSUE TITLE
与已安装的nvm 结合

### ISSUE THREAD

**Issue by 17881055** [1111mp/nvm-desktop#15]
能否与原来已经安装的nvm 配合，使用nvm-desktop 是不是要先卸载已安装的nvm

**Comment by 1111mp** [comment]
是的，`nvm-desktop` 和 `nvm` 之间并没有什么联系，只是项目一开始受 `nvm` 启发，所以给项目取了这个名称（全称 `Node Version Manager Desktop`）。

因为 `nvm-desktop` 和 `nvm` 在底层的实现上是完全不一样的（`nvm` 主要是依赖于 `shell` ），所以相互之间没办法共用的，这一点还望理解。

**Comment by Lonely-flyer** [comment]
下载速度对比nvm夸张的慢，换回nvm了

**Comment by 1111mp** [comment]
> 下载速度对比nvm夸张的慢，换回nvm了

可以在设置里面更改适合自己所在地区的nodejs下载镜像地址。

当然如果觉得用的不可以，使用任何软件都是你的自由。不过相对的更推荐Volta一些。

**Comment by TactfulBean** [comment]
> 能否与原来已经安装的nvm 配合，使用nvm-desktop 是不是要先卸载已安装的nvm

我没卸载nvm也能正常用这个

**Comment by 1111mp** [comment]
@TactfulBean @zhowdom 这是正常的， `nvm-desktop` 和 `nvm` 相互独立没有任何联系的 ，可以同时使用。 只不过可能在系统环境变量先后顺序不同情况下，导致实际使用的可能是 `nvm` 或者 `nvm-desktop`。
