### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hby-abing** [1111mp/nvm-desktop#151]
**Describe the bug**
After installing several Node.js versions, switching between versions works fine, but I'm unable to install dependencies using npm. The installation command gets stuck and then reports an error.

**To Reproduce**
1.Open Visual Studio Code (VSCode).
2.Enter the command npm install in the terminal.
3.The installation progress appears, but it stays still without moving forward, and eventually reports an error after a timeout.
4.View the error message.

**Expected behavior**
The dependencies can be installed smoothly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: acOS Sonoma 14.16.1
 - Arch: arm64
 - Version: 4.0.5

**Additional context**

---

**描述错误**
安装几个node版本后，切换版本没有问题，但是无法使用npm安装依赖，安装命令会卡住，然后报错

**重现步骤**
重现该行为的步骤：
1. 打开vscode
2. 在终端输入命令 npm install
3. 出现安装进度，但是一直不动，超时之后会报错
4. 看到错误

**预期行为**
可以顺利的安装依赖

**截图**

**桌面设备（请填写以下信息）：**
 - 操作系统: macOS Sonoma 14.16.1
 - 架构: arm64
 - 版本: 4.0.5

**附加上下文**
在此添加有关问题的任何其他上下文。

**Comment by 1111mp** [comment]
执行 node -v 和 npm -v 这些命令都正常吗（包括切换node版本之后）

然后麻烦提供一下 npm Install 卡住之后的报错截图，试试是不是因为网络问题造成安装包失败，建议切换一下npm的镜像（建议通过 [nrm](https://github.com/Pana/nrm) 来切换）

**Comment by hby-abing** [comment]
<img width="602" alt="HapiGo 剪贴板 - 2024-12-24 11 5 53" src="https://github.com/user-attachments/assets/e9986749-bde5-4fb6-92e0-4287c60d576a" />
<img width="329" alt="HapiGo 剪贴板 - 2024-12-24 11 26 20" src="https://github.com/user-attachments/assets/56e83275-f3b6-4efe-82e1-1d3b5d3b8eb2" />
<img width="812" alt="HapiGo 剪贴板 - 2024-12-24 11 25 32" src="https://github.com/user-attachments/assets/7bb1261e-5d86-43b6-a428-df643b8c0b71" />
这些命令都是正常的，但就是慢，网络没有问题，我安装了几个版本，其中有个12的版本就没有问题，很快，但是20的版本就不行，那个20.8的版本就一直失败，然后换成20.2的版本，变成了有时很快，有时就一直失败
<img width="932" alt="HapiGo 剪贴板 - 2024-12-24 11 27 27" src="https://github.com/user-attachments/assets/1336f59c-d9d6-4233-bfd8-6084da6910b0" />

**Comment by 1111mp** [comment]
这个应该就是网络问题了 你自己设置一下npm国内的镜像地址 或者 npm install 命令加上 --verbose 输出完整的日志看看
