### ISSUE TITLE
方便加一个叉号可以设置成退出程序还是选择隐藏到托盘吗

### ISSUE THREAD

**Issue by xiaoshuai9999** [1111mp/nvm-desktop#16]

**Comment by xiaoshuai9999** [comment]
可以在设置中设置。我想隐藏到托盘^v^

**Comment by 1111mp** [comment]
可以的，我会在下一个版本加上这个功能的。

请问一下你现在是用的Windows还是Macos系统，目前Macos上是默认最小化，Windows上是直接关闭。到时候两个平台都加上这个功能吧。

**Comment by xiaoshuai9999** [comment]
我是windows

**Comment by 1111mp** [comment]
好的，多谢🙏。

**Comment by 1111mp** [comment]
已在 [Release v2.5.0](https://github.com/1111mp/nvm-desktop/releases/tag/v2.5.0) 中实现。
如果有问题请随时打开此问题。
