### ISSUE TITLE
卸载nvm-desktop后，npm命令不起作用了

### ISSUE THREAD

**Issue by XiaoMo-Donald** [1111mp/nvm-desktop#18]
卸载nvm-desktop后，npm命令不起作用了，这是咋回事呀

![image](https://github.com/1111mp/nvm-desktop/assets/49033970/8cd6968a-9c50-41be-8ceb-37c62e9dcead)

**Comment by 1111mp** [comment]
下载并设置nodejs版本了吗，node -v 也是提示这个吗

或者你打开%HOMEPATH%\.nvmd\bin目录下是否有node.exe npm.exe等文件呢

**Comment by XiaoMo-Donald** [comment]
对的，都是一样的提示，我现在是已经把nvm-desktop卸载了，之前是使用nvm下载管理的node版本

**Comment by XiaoMo-Donald** [comment]
而且好像nvm-desktop卸载不干净，现在nvmd命令还是可以使用，然后导致nvm use命令不生效了现在

**Comment by 1111mp** [comment]
你可以安装[文档](https://github.com/1111mp/nvm-desktop#windows-uninstall)把`nvm-desktop`完全卸载掉。

`nvm-desktop`和`nvm`之间完全不冲突的。`nvm-desktop`所有相关的文件都在`%HOMEPATH%\.nvmd`目录下，以下是几个关键的文件：
- bin 文件夹，保存着`nvmd.exe` `node.exe` `npm.exe` `npm.cmd` `npx.exe` `npx.cmd` `corepack.exe` `corepack.cmd`等文件，这个文件夹路径需要添加到系统环境变量中，终端输入命令时会识别
- versions 文件夹，保存着所有下载的nodejs版本的文件，自文件一般以node版本号为名称，如：`%HOMEPATH%\.nvmd\versions\21.2.0`
- default 文件，文件内容保存着全局设置node版本之后的版本号，如：21.2.0
- settting.json 保存着`nvm-desktop`设置里面的那几个设置信息，如主题、语言、镜像地址等
- packages.json 保存着 npm 全局安装包的引用信息

如果一切正常的话，比如我下载了 `21.2.0` 版本，那么 `versions` 目录下会多出个 `21.2.0` 文件夹，里面是下载的node相关的文件，点击应用该版本之后， `default` 文件会被写入`21.2.0`，之后终端里面输入`node -v` 或者 `npm -v`，相应的会执行 `bin` 目录下的 `node.exe` & `npm.exe`，里面的逻辑是从 `default`文件读取版本号，然后找出完整的node路径：`versions\21.2.0`，然后新建进程并添加`versions\21.2.0`到这个进程的环境变量中，新进程中执行对应的命令，这时候识别到的node版本的`node.exe`就是`versions\21.2.0\node.exe`文件了

整个流程大致是这样，然后安装代码程序的逻辑，如果出现你截图的这种信息，那么就是没有找到对应设置的node的版本的版本号，相关代码在这里：[https://github.com/1111mp/nvmd-command/blob/a3bd9b9d78a8e8a33c5db0a28ef566bde8a8e483/src/run/engine.rs#L6](https://github.com/1111mp/nvmd-command/blob/a3bd9b9d78a8e8a33c5db0a28ef566bde8a8e483/src/run/engine.rs#L6)

所以如果方便的话，可能需要你提供一下相关的信息：
- versions目录下是否已经成功安装了一些node版本（点进去是否存在正常的 node.exe npm npm.cmd 等文件，文件完整不丢失）
- default 文件是否成功写入了设置的版本号

**Comment by XiaoMo-Donald** [comment]
大意了，ok 啦，卸载后要重启一下电脑 ！！！

**Comment by 1111mp** [comment]
最后想确认一下，是卸载`nvm-desktop`之后才导致`npm`命令失效对吗，卸载之前应该都是正常的吧

**Comment by XiaoMo-Donald** [comment]
卸载之前我忘记试了，是卸载之后才试的

**Comment by 1111mp** [comment]
好的 理论上卸载之后命令都是正常的（我本地刚刚测试了是可以的） 不过有可能是卸载之前没有设置过一个默认的版本 所以才出现这个问题。当然如果有问题的话可以参照[这里](https://github.com/1111mp/nvm-desktop/issues/18#issuecomment-1817716861)，谢谢。

**Comment by XiaoMo-Donald** [comment]
ok ok，是的 我安装完成后没有在nvm-desktop下载过任何的node版本

**Comment by 1111mp** [comment]
好的 没问题就好

**Comment by muyaCode** [comment]
我也是这样，重启电脑也不行，需要删掉文件夹：%HOMEPATH%\.nvmd目录，这样就可以了

**Comment by 1111mp** [comment]
如果没有下载或者指定过node版本，不管卸载之前还是卸载之后都会提示对应的命令不存在的，这是正常的。然后可以按照文档完全卸载nvm-desktop。
