### ISSUE TITLE
Error invoking remote method 'all-node-versions': RequestError: Invalid URL

### ISSUE THREAD

**Issue by baomihuayu** [1111mp/nvm-desktop#19]
win平台一直这样，版本是2.4.0
<img width="768" alt="Snipaste_2023-11-19_19-30-43" src="https://github.com/1111mp/nvm-desktop/assets/36615477/452183b8-f634-4a22-92db-31f6f0e4d81c">

**Comment by 1111mp** [comment]
这个错误应该是node下载的镜像地址不正确造成的 请问你这边更改过镜像地址吗 重新打开客户端还是白屏报错吗

**Comment by baomihuayu** [comment]
> 这个错误应该是node下载的镜像地址不正确造成的 请问你这边更改过镜像地址吗 重新打开客户端还是白屏报错吗

第一次是修改过，但是我卸载重装了，还是这样

**Comment by 1111mp** [comment]
你可以安装这里的[文档](https://github.com/1111mp/nvm-desktop#windows-uninstall)查看如何完全卸载`nvm-desktop`。
需要你手动删除 `%HOMEPATH\.nvmd%` 这个文件夹。

当然这种错误也不应该让程序白屏崩溃 我会把这部分修复一下 下个版本带上去。不好意思。

**Comment by baomihuayu** [comment]
> 你可以安装这里的[文档](https://github.com/1111mp/nvm-desktop#windows-uninstall)查看如何完全卸载`nvm-desktop`。 需要你手动删除 `%HOMEPATH\.nvmd%` 这个文件夹。
> 
> 当然这种错误也不应该让程序白屏崩溃 我会把这部分修复一下 下个版本带上去。不好意思。

感谢

**Comment by 1111mp** [comment]
此问题已在 [Release v2.5.0](https://github.com/1111mp/nvm-desktop/releases/tag/v2.5.0) 中修复。
如果有问题请随时打开此问题。
