### ISSUE TITLE
win10 21H2 版本安装 最新版本后 无法运行 

### ISSUE THREAD

**Issue by Tingfenghhh** [1111mp/nvm-desktop#21]
win10 21H2 版本安装 最新版本后 无法运行  我试过了更换安装目录，安装后 双击运行 或者以管理员运行 没反应
![image](https://github.com/1111mp/nvm-desktop/assets/88653280/d690c21a-91be-4cf5-8093-bbe280de901a)

**Comment by 1111mp** [comment]
任务管理器有还在运行的任务吗 如果有请全部停掉 然后还是不行的话 试试将 `%HOMEPATH\.nvmd%` 整个文件夹都删掉再运行呢

**Comment by Tingfenghhh** [comment]
> 任务管理器有还在运行的任务吗 如果有请全部停掉 然后还是不行的话 试试将 整个文件夹都删掉再运行呢`%HOMEPATH\.nvmd%`

任务管理器没有运行的任务 今天才看见这个仓库安装的 第一次运行

**Comment by 1111mp** [comment]
有可能是因为杀毒软件不允许应用运行，因为目前双平台都没有证书签名，可能需要在安全设置里面信任或者允许这个应用运行

**Comment by Tingfenghhh** [comment]
> 有可能是因为杀毒软件不允许应用运行，因为目前双平台都没有证书签名，可能需要在安全设置里面信任或者允许这个应用运行

试过了 把杀毒软件和windows 自带的都关了 也好像不行 ， 我自己的Electron 其他程序 可以正常运行 ，但是可以运行 卸载程序
![image](https://github.com/1111mp/nvm-desktop/assets/88653280/e6e34ad9-2327-4ea1-8164-3c94383b3f03)

**Comment by 1111mp** [comment]
目前我没有windows10 系统的设备测试 不好意思 可以需要你这边提供一些信息：

在 `%HOMEPATH%.nvmd` 目录下是否存在如下文件：
- bin 文件夹，保存着`nvmd.exe` `node.exe` `npm.exe` `npm.cmd` `npx.exe` `npx.cmd` `corepack.exe` `corepack.cmd`等文件，这个文件夹路径需要添加到系统环境变量中，终端输入命令时会识别
- migration 文件 如果正常启动的话文件内容应该是 `5`

然后终端输入 `nvmd -h` 看是否有效

**Comment by Tingfenghhh** [comment]
> 目前我没有windows10 系统的设备测试（windows 11 目前是） 不好意思 可以需要你这边提供一些信息：
> 
> 在 `%HOMEPATH%.nvmd` 目录下是否存在如下文件：
> 
> * bin 文件夹，保存着`nvmd.exe` `node.exe` `npm.exe` `npm.cmd` `npx.exe` `npx.cmd` `corepack.exe` `corepack.cmd`等文件，这个文件夹路径需要添加到系统环境变量中，终端输入命令时会识别
> * migration 文件 如果正常启动的话文件内容应该是 `5`
> 
> 然后终端输入 `nvmd -h` 看是否有效

我重新安装和配置了环境变量，重启电脑后 是可以运行命令的
![image](https://github.com/1111mp/nvm-desktop/assets/88653280/9203c6d7-d61b-4fa3-8b24-5c94793c5d8c)

**Comment by 1111mp** [comment]
这样看的话 程序应该没有任何的报错的 理论上应该能过正常打开窗口界面 

是不是应为系统账号权限的问题 之前有用户反馈：如果用系统管理员就会出现运行不到3s程序就自动退出，但是切换为普通账号权限的时候就正常。

我不太清楚这个的具体原因，如果选择“为所有用户“安装，直接安装在默认的c盘，也会这样吗

**Comment by Tingfenghhh** [comment]
> 这样看的话 程序应该没有任何的报错的 理论上应该能过正常打开窗口界面
> 
> 是不是应为系统账号权限的问题 之前有用户反馈：如果用系统管理员就会出现运行不到3s程序就自动退出，但是切换为普通账号权限的时候就正常。
> 
> 我不太清楚这个的具体原因，如果选择“为所有用户“安装，直接安装在默认的c盘，也会这样吗

没有选过 “为所有用户“安装 ，我一直选的是管理员用户安装 。按理说应该是运行了的 ,在卸载之前会一直提示 程序正在运行  但是无法在任务管理器看到并关闭，导致卸载不了 ,在没重启电脑的前提下，我使用工具强行卸载了  后面再试下 选 “为所有用户“安装

**Comment by 1111mp** [comment]
可以参考 [#44](https://github.com/1111mp/nvm-desktop/issues/44)

 CMD 终端试试运行 start your-install-floder/nvm-desktop.exe , 看会报什么错误  或者在启动命令行末尾加上 --no-sandbox 运行试试能不能启动
 
 试试将软件安装在c盘下全英文的路径下呢（如果安装在中文路径下，中文路径可能可能会造成原因）
 
 最后就是显卡驱动 试试更新一下驱动

**Comment by 1111mp** [comment]
Resolved in [#47](https://github.com/1111mp/nvm-desktop/issues/47)

If you have any questions please feel free to reopen this issue.
