### ISSUE TITLE
How to set node versions bin PATH

### ISSUE THREAD

**Issue by hyrichie** [1111mp/nvm-desktop#22]
node version: v16.20.2(currently)
hope: $HOME/.nvmd/versions/16.20.2/bin

switch node version: v18.18.2
hope: $HOME/.nvmd/versions/18.18.2/bin

**Comment by 1111mp** [comment]
Sorry, I didn't understand your question a bit. Are you asking about how `nvm-desktop` works, or do you need a new feature?

`nvm-desktop` does not switch node versions by setting different environment variables. For more information please see [how-does-it-work](https://github.com/1111mp/nvmd-command#how-does-it-work).

**Comment by hyrichie** [comment]
oh~, thanks!

**Comment by 1111mp** [comment]
You don't have to do this, `nvm-desktop` will automatically do this for you. Of course, it is not necessary to write directly to the system environment variables every time, but the principle is similar to this.

**Comment by hyrichie** [comment]
when i do this:

corepack enable yarn

in my terminal:
![image](https://github.com/1111mp/nvm-desktop/assets/140496925/e3edc84a-1f93-412f-afbc-b8f72e72c464)
![image](https://github.com/1111mp/nvm-desktop/assets/140496925/593a25f5-bf29-46ae-bb44-1dd71ff4d5f2)

**Comment by 1111mp** [comment]
I finally understand what you mean. 😄  

But sorry, `nvm-desktop` currently does not support the `corepack enable` command. If you need to use `yarn` or `pnpm`, please install it through `npm install yarn/pnpm -g`.

But later I will learn `corepack` related behaviors and support it.

**Comment by hyrichie** [comment]
nice, thanks!

**Comment by hyrichie** [comment]
so, you can provide the env setting to solve this problem.

**Comment by 1111mp** [comment]
I need to intercept the `corepack enable` command and then add the corresponding shim to the `$HOME/.nvmd/bin` directory.

Example `corepack enable yarn`:

- Add shim `$HOME/.nvmd/bin/yarn`.(This is what `nvm-desktop` needs to do)
- Shims: `$HOME/.nvmd/versions/16.20.2/bin/yarn` & `$HOME/.nvmd/versions/16.20.2/bin/yarnpkg`. (This is the behavior of `corepack`)

Later, when you run the `yarn -v` command, it is initiated by `yarn` under `$HOME/.nvmd/bin/yarn`. This will create a new process to run the command you enter: `nvmd-command` will internally look for `$HOME/.nvmd/versions/16.20.2/bin/yarn` and then inject it into the environment where this process is running.

> By default it will locate the install directory by running the equivalent of 
`which corepack`, but this can be tweaked by explicitly passing the install 
directory via the `--install-directory` flag.

This is troublesome, it means that `nvmd-command` needs to track these directories. I need some time to think about the implementation.

**Comment by hyrichie** [comment]
nice~

**Comment by hyrichie** [comment]
I solved it by using "corepack enable --install-directory $NVMD_DIR/bin".
![image](https://github.com/1111mp/nvm-desktop/assets/140496925/f4804bef-6ff6-4657-8de5-75b0ffbb229a)

**Comment by 1111mp** [comment]
This is indeed a good idea. 👍 

But this will also bring some side effects:

- After switching the node version, `yarn` or `pnpm` is still generated through `corepack` under the previous node version. You need to re-run the `corepack enable --install-directory $NVMD_DIR/bin` command every time you switch versions (will be overwritten).
- There will be conflicts with `npm install yarn/pnpm -g` to install global packages. I'm not sure if this is the default behavior, I need to look into it.

There may be other questions, but these are the things I'm thinking about right now.

**Comment by 1111mp** [comment]
I've decided on the final solution:

- I will add the `yarn`&`pnpm` gaskets by default in the `.nvmd/bin` directory. After you use `corepack enable` to generate a shim (default is in the `.nvmd/versions/{version}/bin` directory), when you run the `yarn`&`pnpm` commands, `nvmd` will start from `. Find the shim in the nvmd/versions/{version}/bin` directory.

When you use `yarn` or `pnpm` without `corepack enable` and npm is not installed globally, the terminal will prompt: `nvm-desktop: command not find`.

Detailed instructions can be found at: [nvm-desktop: command not found: {lib}](https://github.com/1111mp/nvm-desktop/issues/23)

**Comment by 1111mp** [comment]
Fixed in the latest [Release v2.6.0](https://github.com/1111mp/nvm-desktop/releases/tag/v2.6.0).

If you still have any questions, please feel free to open an issue.

**Comment by hyrichie** [comment]
oh, yeah~
