### ISSUE TITLE
nvm-desktop: command not found: {lib}

### ISSUE THREAD

**Issue by 1111mp** [1111mp/nvm-desktop#23]
This issue aims to explain why the `nvm-desktop: command not found` prompt message appears. Only applies to the following two situations:

- Set the `prefix` option of `npm`. (`npm config set prefix "/path/to/folder"`) That is the directory of the "npm" global installation package has been changed.
- When using `yarn` or `pnpm` through `corepack`. (`corepack enable --install-directory /path/to/folder`) The directory where the executable is generated was changed via the `--install-directory` option.

Therefore, the error prompt of `nvm-desktop: command not found` in the terminal is in line with its respective default behavior. At this time, you need to manually add the `/path/to/folder` directory path to the system environment variable, and then terminal can be correctly identified. However, please note that when adding it to the system environment variable, you need to put the path of `/path/to/folder` before `nvmd` (`$HOME/.nvmd/bin`).

You can download a node version separately to test its respective default behavior without using `nvm-desktop`.

***

这个 issue 旨在解释为何出现 `nvm-desktop: command not found` 提示信息。 只适用于以下两种情况：

- 设置过`npm`的`prefix`选项。 (`npm config set prefix "/path/to/folder"`) 即`npm`全局安装包的目录已更改。
- 通过`corepack`使用`yarn`或`pnpm`时。 (`corepack enable --install-directory /path/to/folder`) 通过 `--install-directory` 选项更改了可执行文件生成的目录。

终端中出现`nvm-desktop: command not find`的错误提示符合其各自的默认行为的。 这时需要手动将`/path/to/folder`目录路径添加到系统环境变量中，然后终端才能正确识别。不过请注意，在添加到系统环境变量的时候，需要将`/path/to/folder`的路径放在`nvmd`（`$HOME/.nvmd/bin`） 之前。

你可以在不使用`nvm-desktop`的情况下单独下载一个node的版本到本地进行测试。当更改过`npm`的全局包安装路径以及通过`corepack enable --install-directory /path/to/folder`命令生成`yarn`&`pnpm`的可执行文件时，需要将其对应的路径添加到环境变量中之后终端才能够正确识别。

Reference:

- [configuring-npm](https://docs.npmjs.com/cli/v10/configuring-npm/folders)

>When in global mode, executables are linked into {prefix}/bin on Unix, or directly into {prefix} on Windows. Ensure that path is in your terminal's PATH environment to run them.

- [corepack-enable](https://github.com/nodejs/corepack#corepack-enable--name)

>Corepack is a zero-runtime-dependency Node.js script that acts as a bridge between Node.js projects and the package managers they are intended to be used with during development. In practical terms, Corepack lets you use Yarn, npm, and pnpm without having to install them.

> `corepack enable --install-directory /path/to/folder`
>
> Add the Corepack shims to the install directories
>
>When run, this commmand will check whether the shims for the specified package 
managers can be found with the correct values inside the install directory. If 
not, or if they don't exist, they will be created.
>
>By default it will locate the install directory by running the equivalent of 
`which corepack`, but this can be tweaked by explicitly passing the install 
directory via the `--install-directory` flag.

**Comment by fyhhub** [comment]
我删除了 npm prefix也不行。。

**Comment by 1111mp** [comment]
@rmd1710714107 根据文档完全卸载`nvm-desktop`: [uninstall](https://github.com/1111mp/nvm-desktop#uninstall)

**Comment by rmd1710714107** [comment]
> @rmd1710714107 根据文档完全卸载`nvm-desktop`: [uninstall](https://github.com/1111mp/nvm-desktop#uninstall)

感谢，已解决

**Comment by klein-moretti** [comment]
我安装成功后，功能也能使用，但是我在用git提交代码的时候代码提交失败，错误如下：
it -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -F C:\Users\57836\AppData\Local\Temp\git-commit-msg-.txt --
nvm-desktop: command not found: node。

**Comment by 1111mp** [comment]
@overrei 请问这边更改过npm的全局安装路径吗

如果没有更改的话，正常情况下通过 `npm install yarn -g` 安装之后，在 `%HOMPATH%\.nvmd\bin` 目录下会多出这些文件：
![image](https://github.com/user-attachments/assets/f26f763e-1c1e-4be4-b9db-92e4558d2953)
你可以检查一下你电脑上该目录下是否存在这些目录 然后确保  `%HOMPATH%\.nvmd\bin` 已经被添加到系统环境变量中（将`%HOMEPATH%`替换成自己电脑的完整路径：比如我自己的：`C:\Users\1111mp\.nvmd\bin`）

然后如果你更改过npm的全局安装包路径的话 比如我本地通过 `npm config set prefix "C:\Users\1111mp\.npm_global"` 更改了全局安装包路径 这时候我运行 `npm install -g @vue/cli` 那么在 `C:\Users\1111mp\.npm_global` 目录下会安装如下文件：
![image](https://github.com/user-attachments/assets/dc483c8d-ae88-4b45-b999-4c6da37573b5)

如果这时候我没有将其加入到环境变量，直接运行 `vue --version`，那么控制台也会报：`nvm-desktop: command not found: "vue"`，但是如果我将其加入到环境变量中：
![image](https://github.com/user-attachments/assets/74222703-cea9-4857-84d4-f5de73ebd031)
然后重新打开一个终端运行：`vue --version`，这时候就正常了，打印：`@vue/cli 5.0.8`
![image](https://github.com/user-attachments/assets/8f83f338-cc4a-425f-a8a9-38bd371e47d8)

所以你按照这个步骤验证一下看看哪里有问题呢 比如在执行这些命令过程中 终端有报错吗 或者执行 `nvmd --help` 是否正常

**Comment by overrei** [comment]
@1111mp 谢谢你的说明
我本地的C:\Users\admin\.nvmd\bin目录和更改的npm全局安装包路径下都已经有yarn文件了，环境变量我按照你的截图，把全路径也配置了。
![image](https://github.com/user-attachments/assets/2fd0620c-e2e8-4c36-b483-ba3585ac0745)
![image](https://github.com/user-attachments/assets/98ed4d4c-953f-4bfa-80fb-0d396435a02f)
![image](https://github.com/user-attachments/assets/0adb1cce-b514-4a9d-a266-e0d1fc0d7bb8)
这些都配置好后，执行`yarn -v`依然提示`nvm-desktop: command not found: "yarn"`
![image](https://github.com/user-attachments/assets/26c23ec1-731a-4f3e-8cfb-cd333d23b6e3)
执行`nvmd --help`也可以正常显示
![image](https://github.com/user-attachments/assets/6f170e0b-85e0-47cb-8c0b-31c915eb2ac1)

**Comment by 1111mp** [comment]
@overrei 你需要把 `D:\nvm-desktop\node_global` 上移一个位置 在 `C:\Users\admin\.nvmd\bin` 上面

然后再重启一下终端运行一下 `yarn --version` 看能否正常

**Comment by overrei** [comment]
@1111mp 
我试了下，好像还是不行
![image](https://github.com/user-attachments/assets/86b3cdc9-116a-49f9-ae59-2d4c2e987c06)
终端也是重启了
![image](https://github.com/user-attachments/assets/e9a387a6-90ad-43ce-a9a3-afad6af3045c)

**Comment by 1111mp** [comment]
@overrei 这个yarn是在当前的node版本下安装的吗 你可以重新安装一下试试 npm install yarn -g 然后再执行 yarn -v 看看 

如果还是不行 那应该就是之前应该在没改npm的prefix之前已经全局安装了yarn 然后更改之后又安装了一次 然后系统变量虽然都加了 但是两者可能有冲突 你可以试着将 `C:\Users\admin\.nvmd\bin` 目录下所有的 yarn相关的文件都手动删除一下 然后再执行 yarn -v 试试能不能用

**Comment by overrei** [comment]
@1111mp 终于好了，就像你说的。我把`C:\Users\admin\.nvmd\bin`目录下的yarn相关文件一删就好了。感谢感谢！

**Comment by Coder-LzZ** [comment]
请问一下 这个node_global是干啥的

**Comment by 1111mp** [comment]
@Coder-LzZ `npm` 通过 `npm config set prefix "/path/to/folder"` 命令设置的全局安装包安装路径

**Comment by Gooopw** [comment]
> @overrei 这个yarn是在当前的node版本下安装的吗 你可以重新安装一下试试 npm install yarn -g 然后再执行 yarn -v 看看
> 
> 如果还是不行 那应该就是之前应该在没改npm的prefix之前已经全局安装了yarn 然后更改之后又安装了一次 然后系统变量虽然都加了 但是两者可能有冲突 你可以试着将 `C:\Users\admin\.nvmd\bin` 目录下所有的 yarn相关的文件都手动删除一下 然后再执行 yarn -v 试试能不能用

@1111mp 您好，我的情况就是您说的下面这种，我修改了npm的prefix，安装完pnpm后删除`C:\Users\admin\.nvmd\bin` 目录下所有pnpm相关文件就可以用。但是有个问题就是每更新pnpm一次就得手动删除`C:\Users\admin\.nvmd\bin` 目录下相关pnpm文件一次。这个有好的解决办法吗？

**Comment by 1111mp** [comment]
@Gooopw npm设置的prefix目录添加到系统环境变量里面去了吗 并且优先级比`.nvmd\bin`目录更高

**Comment by Gooopw** [comment]
> [@Gooopw](https://github.com/Gooopw) npm设置的prefix目录添加到系统环境变量里面去了吗 并且优先级比`.nvmd\bin`目录更高

@1111mp 是我配置的问题，修改环境变量PNPM_HOME的值为C:\Users\Administrator\.nvmd\bin就解决了，谢谢。
