### ISSUE TITLE
2.5.0.0全局包不生效

### ISSUE THREAD

**Issue by yangcore** [1111mp/nvm-desktop#24]
2.5.0.0全局包不生效
![image](https://github.com/1111mp/nvm-desktop/assets/20217483/2b752760-ae3d-4e9e-94be-9575d0e48968)
![image](https://github.com/1111mp/nvm-desktop/assets/20217483/1ad97b37-eaca-41db-81fc-ad2e1e196b2d)
![image](https://github.com/1111mp/nvm-desktop/assets/20217483/26caed42-2a54-495b-a63f-59c0c3fd0b19)

**Comment by 1111mp** [comment]
方便把全局安装的包的名称发给我吗 然后在运行`npm install -g`命令时终端有报错吗

**Comment by yangcore** [comment]
> 方便把全局安装的包的名称发给我吗 然后在运行`npm install -g`命令时终端有报错吗

安装没有报错，这个包是我们自己封装的，再公司私有库里面的，外网访问不了，这个是那个包的入口文件
![image](https://github.com/1111mp/nvm-desktop/assets/20217483/79e029e9-b49e-4974-93a5-61fc91501310)

**Comment by yangcore** [comment]
> > 方便把全局安装的包的名称发给我吗 然后在运行`npm install -g`命令时终端有报错吗
> 
> 安装没有报错，这个包是我们自己封装的，再公司私有库里面的，外网访问不了，这个是那个包的入口文件 ![image](https://user-images.githubusercontent.com/20217483/284776719-79e029e9-b49e-4974-93a5-61fc91501310.png)

![image](https://github.com/1111mp/nvm-desktop/assets/20217483/e3b1298b-ba65-4711-9e9a-4036b3e006ed)

**Comment by yangcore** [comment]
> 方便把全局安装的包的名称发给我吗 然后在运行`npm install -g`命令时终端有报错吗
我刚刚尝试全局安装了下 @vue/cli也是在bin文件夹没有出现可执行命令
![image](https://github.com/1111mp/nvm-desktop/assets/20217483/d0463525-1ba7-49cd-baad-920eb2425395)
![image](https://github.com/1111mp/nvm-desktop/assets/20217483/06d99381-a156-40b2-8be0-8fc9ade482ca)

**Comment by 1111mp** [comment]
我本地测试了一下10.21.0版本 应该不是版本低的问题

用管理员权限打开终端再执行`npm install @vue/cli -g`试试呢

终端输入 `nvmd -h` 正常吗

**Comment by yangcore** [comment]
> 我本地测试了一下10.21.0版本 应该不是版本低的问题
> 
> 用管理员权限打开终端再执行`npm install @vue/cli -g`试试呢
> 
> 终端输入 `nvmd -h` 正常吗

nvmd -h正常的，管理员权限安装也不好使，在bin文件夹内还是没有出现执行文件入口

**Comment by 1111mp** [comment]
这就很奇怪了 

运行`npm root -g`输出什么

该目录下有`@vue/cli`文件吗 比如`versions\10.21.0\node_modules\@vue\cli`，包文件下的`package.json`文件有吗

因为`nvmd`内部拦截npm install -g 命令 在其安装成功之后去解析`versions\10.21.0\node_modules\@vue\cli\package.json`文件的`bin`选项，收集入口`vue`，然后将依赖关系写入到`.nvmd\bin\packages.json`文件并同时往`.nvmd\bin`下添加`yarn.exe yarn.cmd`的垫片

**Comment by yangcore** [comment]
> 这就很奇怪了
> 
> 运行`npm root -g`输出什么
> 
> 该目录下有`@vue/cli`文件吗 比如`versions\10.21.0\node_modules\@vue\cli`，包文件下的`package.json`文件有吗
> 
> 因为`nvmd`内部拦截npm install -g 命令 在其安装成功之后去解析`versions\10.21.0\node_modules\@vue\cli\package.json`文件的`bin`选项，收集入口`vue`，然后将依赖关系写入到`.nvmd\bin\packages.json`文件并同时往`.nvmd\bin`下添加`vue.exe vue.cmd`的垫片
> 
> 但是如果是代码逻辑有误 我本地测试肯定也会出问题 所以在想是不是因为网络问题文件不完整 或者 安装路径错误等 不过感觉跟系统的权限有关 安装`nvm-desktop`时是否选中为所有用户安装 然后`.nvmd`文件默认是在`%HOMEPATH%\.nvmd`目录，比如`c:users\username\.nvmd` 如果当前登录的用户不是之前安装运行的用户 那么很可能是因为权限问题 导致写入文件失败

感谢解答，我大概知道为什么了，因为公司电脑对json文件有加密，只能通过几个白名单内exe文件名去进行访问json,大概是因为这个原因无法访问到package.json文件才导致垫片加载失败的
