### ISSUE TITLE
Sorry, something went wrong. V.some is not a function

### ISSUE THREAD

**Issue by IceCokeY** [1111mp/nvm-desktop#25]
<img width="773" alt="屏幕截图 2023-11-22 211524" src="https://github.com/1111mp/nvm-desktop/assets/95743892/25b512f2-284b-4221-96e0-7f1e08dc9c26">

打开就这样了 重启也不行

**Comment by 1111mp** [comment]
试试将 `%HOMEPATH%\.nvmd` 整个目录删掉再重新运行

**Comment by IceCokeY** [comment]
> 试试将 整个目录删掉再重新运行`%HOMEPATH%\.nvmd`

删掉重新运行就好了，但是已下载安装的记录都没了，是需要重新安装嘛？

PS：我在安装node版本时，经常遇到 下载到还剩几KB的时候卡住 ，最后只能取消重新安装，这个有解决办法嘛?

**Comment by 1111mp** [comment]
这个应该是网络的问题吧 你试试在设置里面更改一下下载node的镜像地址呢 

是的 需要重新下载 刚刚给你的是简单粗暴的方法 因为V.some是编译之后的代码 不太好定位到具体是什么问题

你也可以更改node的下载路径 下次或许再需要这种问题将`%HOMEPATH%\.nvmd`目录删掉 重启之后就不需要重新下载了

**Comment by 1111mp** [comment]
The issue seems to have been resolved.

If you still have any questions, please feel free to open an issue.
