### ISSUE TITLE
i use yarn in project, found nvm-desktop: command not found: yarn

### ISSUE THREAD

**Issue by honeydragon** [1111mp/nvm-desktop#28]

**Comment by 1111mp** [comment]
Please provide some information on why this problem occurs.

How to use `yarn`:

- `npm install yarn -g`
- `corepack enable yarn`

or ?

Have you changed the npm global package installation path? `npm config set prefix "to/path/floder"`

**Comment by 1111mp** [comment]
If you are using `yarn` through the `corepack enable yarn` command, then you can upgrade to [Release v2.6.0](https://github.com/1111mp/nvm-desktop/releases/tag/v2.6.0), which already supports the `corepack enable` command.
