### ISSUE TITLE
没法下载node14

### ISSUE THREAD

**Issue by isuoge** [1111mp/nvm-desktop#30]
mac下（m1） node v14.x 都不支持咋办
老项目需要14  尴尬

**Comment by 1111mp** [comment]
node从16版本才开始支持 apple m1  arm64 芯片的 具体可查看 [https://nodejs.org/dist/](https://nodejs.org/dist/)

**Comment by isuoge** [comment]
有办法解决了，我把用n装的node14.x目录直接丢进nvmd的node目录里可以直接使用,能正确识别出来。

**Comment by isuoge** [comment]
<img width="983" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/17899571/b5bb2722-f092-4f35-91da-aa5f250a5026">

**Comment by isuoge** [comment]
感谢

> 可以这么做，但是不同架构运行会有兼容性的问题 并不是nvm-desktop不支持更低版本，是node自身不支持，不提供arm64架构的编译包，你安装的也是其他架构的，所以实际使用肯定会有兼容性报错的问题的
