### ISSUE TITLE
macos能否设置中增加一个退出时保存菜单栏图标而隐藏dock栏图标

### ISSUE THREAD

**Issue by nelsontech** [1111mp/nvm-desktop#31]
macos能否设置中增加一个退出时保存菜单栏图标而隐藏dock栏图标

**Comment by 1111mp** [comment]
It is implemented in the latest version [Release v2.6.1](https://github.com/1111mp/nvm-desktop/releases/tag/v2.6.1).

If you still have problems, please reopen this issue at any time
