### ISSUE TITLE
全局安装nrm，不能全局使用

### ISSUE THREAD

**Issue by Mophar-gift** [1111mp/nvm-desktop#32]
## npm i -g nrm 全局安装了一个包，但是没有自动生成垫片，但是全局安装的yarn、pnpm都是正常的。

![image](https://github.com/1111mp/nvm-desktop/assets/67857649/4f67327e-1ede-4aae-b9a6-ce42a213e9d5)

**Comment by 1111mp** [comment]
已经定位到问题了 解析包package.json的"bin"字段的规则出了问题 没有和npm的行为保持一致 [bin document](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#bin)

已经在 [commit 1776bc4](https://github.com/1111mp/nvmd-command/commit/1776bc4) 中修复。

我会尽快发个新版本出来，抱歉。

**Comment by 1111mp** [comment]
目前可提供一个临时的方法手动解决一下：
`%HOMEPATH%\.nvmd\bin`目录下，直接将`cli.exe`&`cli.cmd` 重命名为 `nrm.exe` & `nrm.cmd`。

（因为错误的解析规则导致生成的垫片文件出现问题。）

**Comment by Mophar-gift** [comment]
好的 感谢解答

**Comment by 1111mp** [comment]
It's fixed in the latest version [Release v2.6.1](https://github.com/1111mp/nvm-desktop/releases/tag/v2.6.1).

If you still have problems, please reopen this issue at any time
