### ISSUE TITLE
npm install yarn -g 全局下载时，下载路径下载到了安装目录下。没有下载到对应版本的安装目录下

### ISSUE THREAD

**Issue by Stromwyrm-x** [1111mp/nvm-desktop#35]
![屏幕截图 2023-12-12 220400](https://github.com/1111mp/nvm-desktop/assets/76990712/da400466-8995-4b17-a710-88174ebdc086)
我选择的node版本是21.4.0，当我执行命令npm install yarn -g时，它安装到了nodejs目录下，没有安装到21.4.0目录下
![error](https://github.com/1111mp/nvm-desktop/assets/76990712/241e94a5-5636-4ba8-bcd3-91ceb8cdf378)
输入 yarn -v ，命令行显示 nvm-desktop: command not found: yarn

**Comment by 1111mp** [comment]
你终端输入npm root -g 看看npm全局安装包的路径是什么 或者npm config get prefix

**Comment by Stromwyrm-x** [comment]
npm config get prefix的结果是D:\dev\nodejs。如果npm config set prefix D:\dev\nodejs\21.0.4，那么在使用别的版本，例如16.14.0时，npm config get prefix的结果也是D:\dev\nodejs\21.0.4

**Comment by 1111mp** [comment]
这是正常的，这是npm的默认行为，具体可查看[#23](https://github.com/1111mp/nvm-desktop/issues/23)

npm的config保存在系统的.npmrc文件中，不管怎么切换版本，它们会共用这个文件（具体你可以查看npm的文档），所以如果你需要版本之间隔离的话，将.npmrc文件中的prefix选项删除即可，这样就会安装到各自版本node的路径内，即相互隔离。

**Comment by Stromwyrm-x** [comment]
谢谢，照着#23加了环境变量D:\dev\nodejs到C:\Users\24431\.nvmd\bin前面后就可以了。感谢作者！
