### ISSUE TITLE
nvm-desktop 2.6.1 安装后，所有版本页打开空白

### ISSUE THREAD

**Issue by xueyixiao** [1111mp/nvm-desktop#36]
![image](https://github.com/1111mp/nvm-desktop/assets/49152185/612ae47c-fb47-41dc-abc7-5e12931a15e4)
本地刷新，空白，无报错
远程刷新，空白，报错：RequestError: self signed certificate in certificate chain

镜像地址，浏览器可以正常访问
https://nodejs.org/dist/
https://npmmirror.com/mirrors/node

**Comment by 1111mp** [comment]
是不是开启了什么VPN 比如 使用 V2Ray 之类的 这个错误应该是证书认证失败造成的 http代理容易出现这个问题

试试不启用加速器 或者系统设置里面看看是不是使用过代理之类的
