### ISSUE TITLE
新装的node托盘里面不会出现，重启后才有。

### ISSUE THREAD

**Issue by xiaoshuai9999** [1111mp/nvm-desktop#37]
托盘的Global还有项目里面都没有即时刷新，没有出现刚装的node。重启nvm-desktop才有，可以优化吗？我是windows.

**Comment by 1111mp** [comment]
点击 远程刷新 按钮也不行吗

本地刷新 会走缓存，远程刷新 不会走缓存。

还有能告知一下具体的使用场景吗，比如通过什么方式安装新的node版本（nvm-desktop内安装也会出现吗）。谢谢。

**Comment by 1111mp** [comment]
定位到问题的代码了，在安装新版本之后并没有刷新系统托盘和菜单的数据，我这边会修复一下这个问题，抱歉。

**Comment by 1111mp** [comment]
It is fixed in [commit 84135b5](https://github.com/1111mp/nvm-desktop/commit/84135b5) and the next new version will be released as soon as possible.

**Comment by 1111mp** [comment]
It's fixed in the latest version [Release v2.6.2](https://github.com/1111mp/nvm-desktop/releases/tag/v2.6.2).

If you still have problems, please reopen this issue at any time
