### ISSUE TITLE
有可能支持Arm版windows系统吗，现在的情况是能安装但是打不开

### ISSUE THREAD

**Issue by Luohl520** [1111mp/nvm-desktop#38]
有可能支持Arm版windows系统吗，现在的情况是能安装但是打不开

**Comment by 1111mp** [comment]
可以的，我会加一个windows arm架构的版本出来。大概下午会发出来。

不过我只有x64芯片的设备，如果后续还是有问题估计需要你自己按照文档编译了。

**Comment by Luohl520** [comment]
> 可以的，我会加一个windows arm架构的版本出来。大概下午会发出来。
> 
> 不过我只有x64芯片的设备，如果后续还是有问题估计需要你自己按照文档编译了。

好的，你发布后我将测试

**Comment by 1111mp** [comment]
@Luohl520 最新 [Release v2.6.2](https://github.com/1111mp/nvm-desktop/releases/tag/v2.6.2) 版本提供了 Windows arm64 架构的安装包，有时间的话麻烦安装测试一下，非常感谢 🙏

**Comment by Luohl520** [comment]
> @Luohl520 最新 [Release v2.6.2](https://github.com/1111mp/nvm-desktop/releases/tag/v2.6.2) 版本提供了 Windows arm64 架构的安装包，有时间的话麻烦安装测试一下，非常感谢 🙏

测试还是打不开呢，双击后没有反应

**Comment by 1111mp** [comment]
麻烦看一下是否存在%HOMEPATH%\.nvmd目录，如果有，该目录下migration文件的内容可以提供一下吗。

如果这些文件都存在说明主进程运行时成功的，那就应该是在x64设备上编译出的arm64的包还是存在兼容性问题。如果是这样的话可能需要你这边根据文档自己编译一下了。抱歉啊。

**Comment by Luohl520** [comment]
> 麻烦看一下是否存在%HOMEPATH%.nvmd目录，如果有，该目录下migration文件的内容可以提供一下吗。
> 
> 如果这些文件都存在说明主进程运行时成功的，那就应该是在x64设备上编译出的arm64的包还是存在兼容性问题。如果是这样的话可能需要你这边根据文档自己编译一下了。抱歉啊。

没有找到nvmd目录呢
![305C0ADFDE6E9DA969C1D2A962239C8F](https://github.com/1111mp/nvm-desktop/assets/26437746/7fccff81-c1d7-4953-bc2d-f9e0fc231937)

**Comment by 1111mp** [comment]
稍等我下午再重新编译一下。

[windows-on-arm](https://www.electronjs.org/zh/docs/latest/tutorial/windows-arm) 按照文档应该是不需要做一些特殊处理的（nvm-desktop没有本机依赖）。

**Comment by 1111mp** [comment]
x64平台交叉编译arm64还是存在问题，等我以后有arm64的设备之后再上传对应的安装包。抱歉。

在此之前你可以根据文档 [Develop-and-build](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#develop-and-build) 在本地自己编译。谢谢。

**Comment by Luohl520** [comment]
我在windows x64 下想打包 windows on arm64 的可执行程序，报错，
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/128c3611-16f1-4f77-a3c0-2952b11d453d)
请问我应该怎么处理

打包windows x64 是OK的。

**Comment by 1111mp** [comment]
除了安装 aarch64-pc-windows-msvc 的target 然后还需要在 VS 中安装对应架构的 c++ 编译工具 你应该需要安装 x64 的

或者你可以使用我已经编译好的 [https://github.com/1111mp/nvmd-command/releases/tag/v2.6.2](https://github.com/1111mp/nvmd-command/releases/tag/v2.6.2)

**Comment by Luohl520** [comment]
> targe

我已将按照要求安装了 编译工具，
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/62eed98d-9e7b-43f5-bf5d-2d77d5aee8ed)
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/064b2449-661a-4fe0-ba1f-165ab31a524d)

执行cargo build --target aarch64-pc-windows-msvc 依然报错，
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/9649a673-1e9d-4ea5-ae4a-e59300bdd429)
执行 cargo build --release 正常打包完成

![image](https://github.com/1111mp/nvm-desktop/assets/26437746/f71bf18a-2eb4-48b5-b0cb-4ccb38e9e8d8)


也许应该使用你打包出来的文件吧。
![8291022f46e2b001036ab2734d402279](https://github.com/1111mp/nvm-desktop/assets/26437746/a7ef9d13-aa6a-48ab-9699-04a184384250)

**Comment by 1111mp** [comment]
![image](https://github.com/1111mp/nvm-desktop/assets/31227919/6064cd48-5102-4484-b1d4-e25c5a4c1424)

这是我电脑上VS的 看起来应该没什么问题 安装结束之后电脑重启了吗

 cargo build --release 命令是会根据电脑的platform和arch来打包的 跨平台需要指定 --target
 
 你也可以从这里获取一些有用的信息：[using_rust_on_windows_for_arm](https://www.reddit.com/r/rust/comments/tpfvaj/using_rust_on_windows_for_arm/)

**Comment by Luohl520** [comment]
我在windows server 2012 上成功编译出 Arm版可执行文件，开始执行yarn start 命令时是可以正常执行的，程序也正常启动了的，然后我就打包yarn run package，打包时就报错了，
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/66f0c989-7195-4c9c-bd54-5d2f01469a17)

然后我再次执行 yarn start  也不可以了，报上面一样的错

我是哪里环境变量不对吗？

**Comment by 1111mp** [comment]
你本地的node是通过`nvm-desktop`安装的对吧 那么你先查看一下 `%HOMEPATH%\.nvmd\bin` 目录下的文件是否齐全（[maybe-somethings-you-need-to-know](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#maybe-somethings-you-need-to-know)）
<img width="832" alt="Screenshot 2024-01-05 at 13 00 33" src="https://github.com/1111mp/nvm-desktop/assets/31227919/7c3a2078-afc5-4c61-8e31-bc0e026778f3">

或者终端输入 `node --version` `npm --version` 看是否都正常

或者重启一下终端呢

**Comment by Luohl520** [comment]
> 你本地的node是通过`nvm-desktop`安装的对吧 那么你先查看一下 `%HOMEPATH%\.nvmd\bin` 目录下的文件是否齐全（[maybe-somethings-you-need-to-know](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#maybe-somethings-you-need-to-know)） <img alt="Screenshot 2024-01-05 at 13 00 33" width="832" src="https://private-user-images.githubusercontent.com/31227919/294398552-7c3a2078-afc5-4c61-8e31-bc0e026778f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzEyODgsIm5iZiI6MTcwNDQzMDk4OCwicGF0aCI6Ii8zMTIyNzkxOS8yOTQzOTg1NTItN2MzYTIwNzgtYWZjNS00YzYxLThlMzEtYmMwZTAyNjc3OGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA1MDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMDA3ODFmNzk0ZjE4OWFhMmIwZWYyN2Y5MWE2M2FlZmRjOTYyOTE1MTBiNjFhM2IwZDdhODE2NjIxMDUwMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDF3NGWlIWrrbrbF2Qqv9BuC9XKGzkS3qq1cLCI5uA4">
> 
> 或者终端输入 `node --version` `npm --version` 看是否都正常
> 
> 或者重启一下终端呢

![image](https://github.com/1111mp/nvm-desktop/assets/26437746/547e0cfe-5e36-4d38-ba68-8293cc669709)
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/5229894b-6d8b-4f37-9bce-167a7705ae2a)
有些文件丢失了，npm也出问题了

**Comment by 1111mp** [comment]
按照你的截图 你的node应该不是在`.nvmd\bin`下 试试运行 `where node` 查看一下真实的路径呢 

然后你把`.nvmd`整个目录删掉重新安装node 再编译试试 

按照编译文档：https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#develop-and-build 你需要创建这两个文件："./assets/sources/x64.exe" & "./assets/sources/arm64.exe" 就是nvmd.exe 重命名为 `x64.exe` & `arm64.exe`

**Comment by Luohl520** [comment]
> 按照你的截图 你的node应该不是在`.nvmd\bin`下 试试运行 `where node` 查看一下真实的路径呢
> 
> 然后你把`.nvmd`整个目录删掉重新安装node 再编译试试
> 
> 按照编译文档：https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#develop-and-build 你需要创建这两个文件："./assets/sources/x64.exe" & "./assets/sources/arm64.exe" 就是nvmd.exe 重命名为 `x64.exe` & `arm64.exe`
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/c57c0c49-d1c1-4d95-92a0-d260fbc5fc82)
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/329c17fa-313f-4f51-91a7-a185f1ea4c11)
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/7622d094-57e3-48f1-96bc-197384319324)

**Comment by 1111mp** [comment]
这个错误好像跟项目没关系 是系统环境的问题吧 你试试这里的方法对你有用吗： https://stackoverflow.com/questions/59562969/error-spawn-cmd-enoent-while-starting-react-app

`Goto > Control Panel\System and Security\System\Advance system setting\Enviroment variable and set system variables path C:\Windows\System32\ variable and restart your System.`

**Comment by Luohl520** [comment]
> 这个错误好像跟项目没关系 是系统环境的问题吧 你试试这里的方法对你有用吗： https://stackoverflow.com/questions/59562969/error-spawn-cmd-enoent-while-starting-react-app
> 
> `Goto > Control Panel\System and Security\System\Advance system setting\Enviroment variable and set system variables path C:\Windows\System32\ variable and restart your System.`

我现在编译出了 winX64版本，请问怎么编译arm64呢
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/6070c0ce-dab8-4de8-b5bc-669b9f90b4a4)

**Comment by Luohl520** [comment]
> [Command Line Interface](https://www.electron.build/cli) 这里是 `electron-builder` 的文档，如果你本地是`main`分支下最新的代码的话，运行`yarn run package`应该会打包出 `x64` & `arm64` 的包的，具体配置：[package.json#L199](https://github.com/1111mp/nvm-desktop/blob/228e954035f1622604e2ba7d53588ce793a68a5e/package.json#L199)
> 
> ```json
> "win": {
>       "target": [
>         {
>           "target": "nsis",
>           "arch": [
>             "x64",
>             "arm64"
>           ]
>         }
>       ],
>       "requestedExecutionLevel": "requireAdministrator"
>     },
> ```

好消息是 我在arm 版win上 yarn start 成功运行了起来
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/9572cb39-e00f-4648-9cf0-dd70e3af598c)
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/d04c7726-741c-4609-ac2c-7650c550994c)
![image](https://github.com/1111mp/nvm-desktop/assets/26437746/ec5e5bfa-502b-48ac-8db2-7eee0ffcc0b3)

坏消息是 yarn run package 打包出来的文件依旧是安装后打不开

![image](https://github.com/1111mp/nvm-desktop/assets/26437746/8f00d7ae-543c-45a3-9e85-727fb9a1ea32)

**Comment by 1111mp** [comment]
你在终端运行 `start your_floder\nvm-desktop.exe` 试试报什么错

你打包的时候 `./assets/sources/` 目录下有 `x64.exe` & `arm64.exe` & `temp.cmd` 文件吗 （node的 `import { platform, arch } from 'node:process';` arch在arm平台上的值是 `arm64` 吗 我担心是 `arm` 如果是`arm`的话 那么`arm64.exe` 需要改成 `arm.exe` ）

你可以查看 `%HOMEPATH%\.nvmd` 目录下文件都否都存在 `migration`文件的内容是否为 `8`

**Comment by 1111mp** [comment]
https://tencentcloud.csdn.net/65979e91dafaf23eeaee4394.html

试试这个呢

**Comment by 1111mp** [comment]
好的，非常感谢，特别是花了这么长时间去测试啊，后续我会调研一下为什么申请admin权限会造成启动奔溃的问题，所以现在结论是你在x64架构下打出的arm64包可以正常启动对吗

**Comment by Luohl520** [comment]
> yarn run package

之前是在Arm架构下打的包，可以正常运行，我又特地在X64架构下打了包，复制到arm架构下测试，是能够正常运行的，且因为window11 可以转译运行64程序，所以X64的的包也是可以运行的，只是相对于原生Arm64 会有性能损失。

**Comment by 1111mp** [comment]
当设置成highestAvailable之后运行，会提示申请管理员权限吗，因为nvm-deaktop需要申请管理员权限运行（第一次安装的时候添加系统环境变量的命令），还是自动降级为普通的用户权限。

**Comment by Luohl520** [comment]
> 当设置成highestAvailable之后运行，会提示申请管理员权限吗，因为nvm-deaktop需要申请管理员权限运行（第一次安装的时候添加系统环境变量的命令），还是自动降级为普通的用户权限。

没有提示，但是我看安装后环境变量有添加，能正常启动

**Comment by 1111mp** [comment]
好的 最后麻烦你测试一下呢 就是将 `%HOMEPATH%\.nvmd` 整个目录全部删除 同时删除系统环境变量 然后再启动 `nvm-desktop`  测试一下写入环境变量是否正常 （因为担心是之前你本地通过 yarn run start 启动项目写入的）

我稍后也会在windows x64 上测试一下，但是目前不太方便 

真的非常感谢 🙏

**Comment by Luohl520** [comment]
> 好的 最后麻烦你测试一下呢 就是将 `%HOMEPATH%\.nvmd` 整个目录全部删除 同时删除系统环境变量 然后再启动 `nvm-desktop` 测试一下写入环境变量是否正常 （因为担心是之前你本地通过 yarn run start 启动项目写入的）
> 
> 我稍后也会在windows x64 上测试一下，但是目前不太方便
> 
> 真的非常感谢 🙏

 .nvmd目录删除，环境变量删除，重新打开程序，目录自动创建，环境变量自动添加，程序正常运行删除

**Comment by 1111mp** [comment]
好的 谢谢 🌹
