### ISSUE TITLE
[feat]: Manage NPM download sources

### ISSUE THREAD

**Issue by RSS1102** [1111mp/nvm-desktop#4]
Can view the current source using string display,
and list the current mainstream sources in China, such as taobao.org, etc.

**Comment by 1111mp** [comment]
In fact, this address can already meet your needs: https://npmmirror.com/mirrors/node, which is a cdn service. You can enter this URL in the browser and view the page content. It should show the best download address.
>NoSuchKey The specified key does not exist. 64E48A2C2C162E3231E4967B npmmirror.oss-cn-shanghai.aliyuncs.com binaries/node 0026-00000001

**Comment by RSS1102** [comment]
> 其实这个地址已经可以满足你的需求了：https://npmmirror.com/mirrors/node，这是一个cdn服务。你可以在浏览器中输入该URL并查看内容。应该会显示最佳下载地址。
> 
> > 64E48A2C2C162E3231E4967B npmmirror.oss-cn-shanghai.aliyuncs.com 二进制文件/节点 0026-00000001存在
> 
> 当然，如果您有强烈的需求，我希望您能详细说明您的需求，因为我可能不太清楚您的需求。当然，我们非常欢迎您的公关。

ok,I will reconsider my requirements and if possible, I will add a PR for your review next month.thanks.
