### ISSUE TITLE
报错 找不到 npm nvm-desktop:command not found:npm

### ISSUE THREAD

**Issue by xmasuhai** [1111mp/nvm-desktop#40]
Win11
NODE Version: v16.20.2
同时装了 nvm

**Comment by 1111mp** [comment]
nvm-desktop和nvm之间其实并没有什么联系的，只是已开始受它启发，你需要在mvm-desktop中先安装一个版本的node

也可以查看这个问题 [#15](https://github.com/1111mp/nvm-desktop/issues/15)

**Comment by 1111mp** [comment]
[#15](https://github.com/1111mp/nvm-desktop/issues/15) 重复的问题，如果你本地运行过`corepack disable npm`，那么对应的npm会被remove掉的，这是node的默认行为，你也可以查看 [#23 nvm-desktop: command not found: {lib}](https://github.com/1111mp/nvm-desktop/issues/23)查看更多信息。

如果以上问题都不符合，请随时重新发开这个issue（还请提供更多的信息）。
