### ISSUE TITLE
最新版软件在Windows 11 家庭中文版22H2无法打开界面

### ISSUE THREAD

**Issue by Git-cqs** [1111mp/nvm-desktop#44]
问题如题，不能打开软件，但是命令行命令能输入
![微信截图_20240101192720](https://github.com/1111mp/nvm-desktop/assets/65646209/5e477b40-3d5e-4284-a955-a79b97dfac92)

**Comment by 1111mp** [comment]
目前双平台都没有证书进行签名认证，所以先试试在系统设置信任`nvm-desktop`程序再运行呢，如果用了第三方安全软件，可能需要单独设置一下

或者安装的时候试试选择“为所有用户安装”

如果都不行试试打开 CMD 终端试试运行 `start your-install-floder/nvm-desktop.exe` , 看会报什么错呢

（如果任务管理器中有nvm-desktop的进程，请先关闭该进程）

**Comment by 1111mp** [comment]
试试将软件安装在c盘下全英文的路径下呢（中文路径可能可能会造成原因）

或者在启动命令行末尾加上 `--no-sandbox` 运行试试能不能启动

最后就是显卡驱动 试试更新一下驱动

**Comment by Git-cqs** [comment]
是因为中文的原因，谢谢你了，我换成英文就没问题了

**Comment by 1111mp** [comment]
好的 问题解决了就好 🌹 

那么我就先把这个问题关闭了 后续如果还遇到任何问题都可以随时重新打开这个issue。 😄
