### ISSUE TITLE
vscode或者websotrom 里运行会报错在系统自带终端npm run dev不会

### ISSUE THREAD

**Issue by anganing** [1111mp/nvm-desktop#46]
webstorm下：
![image](https://github.com/1111mp/nvm-desktop/assets/63218247/d5aa39cd-8130-466b-bbc3-c5265020d64e)

vscode下：
![image](https://github.com/1111mp/nvm-desktop/assets/63218247/1957e7d9-8f6d-4a0a-b9fb-7e48c166e327)

windows terminal:
![image](https://github.com/1111mp/nvm-desktop/assets/63218247/a0b7c7f5-f9ac-446c-abe6-825754ab5cf4)

**Comment by 1111mp** [comment]
vscode和webstorm 里面项目是启动不起来吗 截图里是一些warning 项目应该能够启动吧 这个应该是node自己的行为 你可以试试直接使用本地的node执行试试 就是node的安装目录 `your_installed_floder\node20.0.0` 添加到系统环境变量下（优先级比`.nvmd\bin`高），这样就直接使用安装的node 不会经过nvm-desktop的代理了 然后在vscode下启动项目 应该是会得到同样的输出的

**Comment by anganing** [comment]
就是在vscode或者webstorm里用nvmd的代理就这样，在系统里的cmd或者powershell运行都没问题 之前我看到过类似一个这样的问题但是不知道他是在哪里发布的了

**Comment by 1111mp** [comment]
你可以试试不用nvmd，直接本地安装node运行项目 看会不会有这些warning提示

**Comment by anganing** [comment]
我电脑重启后就可以了😂，安装使用教程里建议重启电脑

**Comment by 1111mp** [comment]
这个问题应该是node自身的问题 nvmd不会中间做任何处理 可能跟vscode&websotrm终端对于stdout流的处理方式有关（因为一些环境或者其他原因）

那么这个问题就先关闭了 后续有问题也可以随时重新打开。谢谢。
