### ISSUE TITLE
Win11 23H2无法使用nvm desktop问题

### ISSUE THREAD

**Issue by XF-Store** [1111mp/nvm-desktop#47]
![微信截图_20240106094737](https://github.com/1111mp/nvm-desktop/assets/67722408/89d5e530-4d39-47b3-b525-1ea1c39ad4c6)

上面是我的设备版本号截图

下载的是以下三个版本：
![微信截图_20240106094846](https://github.com/1111mp/nvm-desktop/assets/67722408/da88b5d9-6bdf-4498-8e21-f4b852f7d85b)

但是双击打开都是无反应的，重启电脑不行，软件兼容性疑难解答使用后可以安装。

安装后双击程序exe程序也是无反应，托盘和界面什么都没有，也无报错

我使用Win10 2016 LTSC就可以安装运行，使用Win10 21H2和Win11 23H2均无效，无法打开

Win11 23H2安装最新版无反应，安装nvm desktop v2.5.0安装可以弹出安装窗口，安装后还是无法运行程序

是需要安装什么运行库吗？挺喜欢这个程序的，但是兼容性感觉好差啊

**Comment by TYZSAMA** [comment]
可以麻烦对其他win版本或以上win版本做一下兼容吗？

**Comment by 1111mp** [comment]
你的设备是x64架构的 所以直接下载x64的文件安装即可 请下载最新版本的安装

能够理解你的心情 但是真实的用户环境还是挺复杂的 并不能保证绝对的没有任何问题（无论是自己的代码还是electron本身的问题），所以还请耐心提供一些额外的信息帮助定位到问题并最终解决问题：

- 试试在终端运行 `start your-install-floder/nvm-desktop.exe` 看看会显示什么错误 （如果任务管理器中有nvm-desktop的进程，请先关闭该进程）

- 如果安装路径有中文的话 可能会造成这种情况 可以参考 [#44](https://github.com/1111mp/nvm-desktop/issues/44)

**Comment by XF-Store** [comment]
![微信截图_20240106102003](https://github.com/1111mp/nvm-desktop/assets/67722408/2a03966e-0404-4fa5-bacf-160c7c05acc0)

这个是cmd运行结果，您看一下，是什么问题

**Comment by 1111mp** [comment]
谢谢 那么很可能跟这里是一样的原因：https://github.com/1111mp/nvm-desktop/issues/38#issuecomment-1879472407

而且这个问题似乎是偶现的 并不是所有的windows用户都会这样 一会儿我会更新一下最新的安装文件 （更新好了会告知你 你再下载看是否能够运行）

**Comment by XF-Store** [comment]
好的，测试了管理员运行也是不行的，程序根本没有运行。

我等新版本测试一下

**Comment by 1111mp** [comment]
https://github.com/1111mp/nvm-desktop/releases/tag/test 

你试试下载到本地安装是否可以运行 （右键以管理员运行 安装文件）

**Comment by XF-Store** [comment]
可以运行了，可以发布新版本了

安装需要管理员运行才出现安装窗口

**Comment by 1111mp** [comment]
[Release v2.6.2](https://github.com/1111mp/nvm-desktop/releases/tag/v2.6.2) windows平台的安装包都已经更新 重新下载安装即可 

安装文件需要以管理员运行 这个是系统权限问题（安全性） 这个是正常的 因为目前双平台都没有证书签名 这一点抱歉

那么我就先关闭这个issue了 当然后续如果有任何问题都可以随时重新开启。谢谢。
