### ISSUE TITLE
建议node列表区分下LTS和Current版本

### ISSUE THREAD

**Issue by BG7ZAG** [1111mp/nvm-desktop#49]
建议node列表区分下LTS和Current版本，谢谢~

**Comment by BG7ZAG** [comment]
> 目前`lts`版本的话会有对应的`tag`： <img alt="Screenshot 2024-01-24 at 11 10 14" width="1032" src="https://private-user-images.githubusercontent.com/31227919/299165875-ca774974-3357-486a-b500-66cc50b6f77c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjg1MzEsIm5iZiI6MTcwNjA2ODIzMSwicGF0aCI6Ii8zMTIyNzkxOS8yOTkxNjU4NzUtY2E3NzQ5NzQtMzM1Ny00ODZhLWI1MDAtNjZjYzUwYjZmNzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAzNTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YTEyZTM0NWI3M2I0ZTk0OTUxN2Q3MmU1N2E5MTE4OWE1NDE5ODAzNTdlODgyNTBkY2NjODVjNDhiNGUzMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o1NimU07Kn3Iqe3-sVQOgru2G4h0VathMCZN_bt1WbQ">
> 
> 你可以在table的`header`中根据名称快速搜索该名称。
> 
> 或者你有更好的建议也可以详细说明一下，谢谢。

抱歉，之前没注意到这个tag是lts的。

下面这个是宝塔上的node管理界面，可供参考。当前目前这样也是不错的，只是lts标识有点不太明了。

![image](https://github.com/1111mp/nvm-desktop/assets/16408650/72220dff-24d4-4be2-9b60-a86876b3c449)

再次感谢你的回复说明！

**Comment by 1111mp** [comment]
客气了，后面我会优化一下这里的体验问题。谢谢。
