### ISSUE TITLE
【建议】希望加个全局node版本的设置界面

### ISSUE THREAD

**Issue by JS-an** [1111mp/nvm-desktop#50]
希望可以在界面上切换全局的node版本，或者可以在找不到 .nvmdrc 的情况下，自动用设置的默认node。
PS：这项目真挺好用的！

**Comment by JS-an** [comment]
不好意思，找到了，原来在这里
![image](https://github.com/1111mp/nvm-desktop/assets/25688878/2feec2e1-329a-4d80-be0c-06b5259eb072)

**Comment by 1111mp** [comment]
version和installed version界面里面设置的就是全局默认的版本，然后只有project界面才是给项目设置的

然后查找node版本的策略就是：当前工作目录有.nvmdrc并且设置了版本号则使用该版本，如果没有就使用全局默认的。

这个菜单栏是为了不需要每次都打开主界面直接在菜单栏就可以设置，更方便一些。当然也提供了一个命令行工具，你可以运行nvmd -h来查看所有的命令。nvmd use {版本号}设置全局默认的版本，为项目设置加上--project
