### ISSUE TITLE
【建议】镜像源可以设置下拉选泽

### ISSUE THREAD

**Issue by 184177677** [1111mp/nvm-desktop#51]
【建议】镜像源可以设置下拉选泽

**Comment by 1111mp** [comment]
你的意思是固定写死几个选项 还是追踪用户的使用记录（将使用过路径的历史记录作为下拉选项）

固定写死肯定体验不是很好 追踪记录的话需要校验`url`的合法性或者可用性 

这个后续我会添加一下这个功能

**Comment by BG7ZAG** [comment]
> 你的意思是固定写死几个选项 还是追踪用户的使用记录（将使用过路径的历史记录作为下拉选项）
> 
> 固定写死肯定体验不是很好 追踪记录的话需要校验`url`的合法性或者可用性
> 
> 这个后续我会添加一下这个功能

其实可以写一两个固定的，外加自定义。固定的可以是npm官网和npmmirror就行

**Comment by 1111mp** [comment]
也可以，这个后续我会加上。

目前在对ui进行重构，迁移到esmodule的工作，有点东西要处理，不会那么快。

**Comment by BG7ZAG** [comment]
> 也可以，这个后续我会加上。
> 
> 目前在对ui进行重构，迁移到esmodule的工作，有点东西要处理，不会那么快。

要不是ui重构，我有空也提个pr
![03BC2CD2](https://github.com/1111mp/nvm-desktop/assets/16408650/c75856eb-6a7e-484d-832f-d3e02c39439f)

**Comment by 1111mp** [comment]
该功能目前已经实现 但是因为目前没有设备所以发布不了 得等到年后了 

[commit e057d62](https://github.com/1111mp/nvm-desktop/commit/e057d62)

默认提供这两个镜像地址（可上下切换选择）：
<img width="1031" alt="Screenshot 2024-02-06 at 11 58 45" src="https://github.com/1111mp/nvm-desktop/assets/31227919/ac5a997f-2a4d-4450-8eda-bebe9d8fa9f8">

也支持自定义，输入自己想要的镜像地址会保存到记录（点击设置弹窗的`OK`确认按钮之后才会保存），但是最多会保存5条记录（最近使用的5条记录）：
<img width="1036" alt="Screenshot 2024-02-06 at 11 59 09" src="https://github.com/1111mp/nvm-desktop/assets/31227919/b5fda621-1141-4e9f-93d1-8948b4e4c515">

**Comment by 1111mp** [comment]
这个功能目前已经在最新的 [Release v3.1.0](https://github.com/1111mp/nvm-desktop/releases/tag/v3.1.0) 中提供支持

那么我就先把这个`issue`给关掉了 当然后续如果有任何问题都可以随时重新打开 谢谢

**Comment by mrxxx66** [comment]
包的仓库镜像源能加一个不

**Comment by 1111mp** [comment]
@mrxxx66 `nvm-desktop` 来做这个事情侵入性就太高了，你可以使用 [nrm](https://github.com/Pana/nrm) 包来管理，这样更方便。

**Comment by mrxxx66** [comment]
内置几条命令行，模拟执行换源命令，不直接修改配置文件，应该没侵入性吧。

**Comment by mrxxx66** [comment]
> @mrxxx66 `nvm-desktop` 来做这个事情侵入性就太高了，你可以使用 [nrm](https://github.com/Pana/nrm) 包来管理，这样更方便。

我尝试下
