### ISSUE TITLE
终端中执行正常，vscode,wenstrom中运行不存在

### ISSUE THREAD

**Issue by lppoi** [1111mp/nvm-desktop#52]
nvmd的环境变量在我放在了系统变量里。
![image](https://github.com/1111mp/nvm-desktop/assets/64509267/4ec2413b-e000-4249-8f8c-ecca35aac464)

开发者你好，我使用的Win11系统，目前碰到的问题是，在终端执行nvmd -h  node -v等命令都正常，在vscode中的终端执行却报错命令不存在，但是使用管理员模式后可以正常执行。这个问题应该如何解决，我看其他issue好像没有类似的解决方案。
## 系统终端
![image](https://github.com/1111mp/nvm-desktop/assets/64509267/eda930cb-33a6-4ea9-b4c6-1b52ce48f947)
## vscode
![image](https://github.com/1111mp/nvm-desktop/assets/64509267/e5a23598-d5ef-43ad-9821-80a8160aaee2)

**Comment by 1111mp** [comment]
`vscode`终端的类型是什么（`cmd`还是`powershell`）

这个可能跟你计算机的账号权限有关 你是管理员账号吗 试试右键`%HOMEPATH%\.nvmd`文件 查看一下权限是什么

如果可以的话试试将`%HOMEPATH%\.nvmd\bin`系统环境变量放在第一位呢 

然后重启`vscode`试试

**Comment by lppoi** [comment]
vsc里是powershell
我当前用户是管理员，我在外面用cmd执行也说不存在，管理员运行能执行
环境变量放系统变量第一位了
奇了怪了

**Comment by lppoi** [comment]
..也不知道怎么好了 ，卸载完又装了一次，又装了volta， 然后重启电脑 能正常启动了，太玄了

**Comment by 1111mp** [comment]
应该是跟系统的权限有关 重启之后文件被赋予了管理员权限吧

如果后续还有问题的话 可以随时重新打开这个`issue`
