### ISSUE TITLE
Linux amd版本应该下载哪个?

### ISSUE THREAD

**Issue by wxyShine** [1111mp/nvm-desktop#53]
只看到了Liunx arm版本，amd应该下载哪个？

**Comment by 1111mp** [comment]
看你系统的架构 一般是`x64`或者`arm64` 你可以在系统信息里面查看一下 

目前 `Linux` 系统的话还没有发出正式的安装包（虽然有`arm64`的 但是还是有点问题） 你可以查看：[https://github.com/1111mp/nvmd-command/issues/5](https://github.com/1111mp/nvmd-command/issues/5)

后面有时间我会补发一下。因为本地在进行重构 可能没有那么快 还望理解

**Comment by 1111mp** [comment]
最新的 [Release v3.0.0](https://github.com/1111mp/nvm-desktop/releases/tag/v3.0.0) 提供了`Linux` 的 `arm64`和`x64`架构的安装包 同时修复了兼容性问题，你可以下载试用一下。

那么我就先把这个issue给关掉了 当然后续如果有任何问题都可以随时重新打开 谢谢

**Comment by wxyShine** [comment]
好的 感谢
