### ISSUE TITLE
页面样式有点问题

### ISSUE THREAD

**Issue by lsrweb** [1111mp/nvm-desktop#60]
![image](https://github.com/1111mp/nvm-desktop/assets/61956525/869ea4b7-ea6e-414f-a301-58e5fdb56209)
路径文本展示不全

另外,这下图右边俩按钮是就是这样设计小一号的嘛
![image](https://github.com/1111mp/nvm-desktop/assets/61956525/06680af6-c832-40fe-b62f-5da04e22fa58)

不好生意,做前端测试多了,感觉有点怪
但是总体来说,99分

**Comment by 1111mp** [comment]
> 另外,这下图右边俩按钮是就是这样设计小一号的嘛

是的 按钮是高度是故意小一点的（`24px`），左边的输入框和`View`高度为`32px`。目的是想将按钮和`table`操作分开。

> 路径文本展示不全

是本身路径有空格还是显示的时候会这样 麻烦能够将完整的路径复制出来看一下吗 我本地测试一下 如果有问题的话应该是这一行的代码有问题：[/src/renderer/src/pages/projects/index.tsx#L196](https://github.com/1111mp/nvm-desktop/blob/e057d62fd85208fa7ca0d5ecc49bdddeefa76570/src/renderer/src/pages/projects/index.tsx#L196)

**Comment by lsrweb** [comment]
**D:\DevCode___\A_XJ_YingFeng\sub-zljc** 
这是项目路径

32px那个大点的我觉得挺好

**Comment by 1111mp** [comment]
好的 感谢 🌹 

已经定位到问题了，元素行高太低造成的（`css`样式。 不仅仅是下面的`下横线`，有些字母（比如`g`）下面都被遮住了，我会在下个版本修复这个问题。

> 32px那个大点的我觉得挺好

👌 会随着下个小版本一起发布 非常感谢。

不过目前自动化测试还有点问题 得等到[webdriverio](https://github.com/webdriverio/webdriverio)这边一个`issue`修复再发出下个版本 所以可能不会那么快 还望见谅

**Comment by lsrweb** [comment]
期待更好,一起进步
![image](https://github.com/1111mp/nvm-desktop/assets/61956525/af84e346-fe18-4221-8d8d-6630aaa4ec73)

**Comment by 1111mp** [comment]
这个问题目前已经在最新的 [Release v3.1.0](https://github.com/1111mp/nvm-desktop/releases/tag/v3.1.0) 中修复

那么我就先把这个`issue`给关掉了 当然后续如果有任何问题都可以随时重新打开 谢谢

**Comment by lsrweb** [comment]
好哒!!Thanks♪(･ω･)ﾉ谢谢,元宵节快乐

**Comment by 1111mp** [comment]
谢谢，也祝你元宵节快乐🏮
