### ISSUE TITLE
【建议】后面会有docker镜像吗

### ISSUE THREAD

**Issue by hzh11012** [1111mp/nvm-desktop#64]

**Comment by 1111mp** [comment]
在我个人的认知里，感觉在`Docker`场景下应该不太需要这个功能吧，一般部署项目的时候该项目都会有一个`.dockerfile`文件，然后在该文件配置中指定`Nodejs`的版本就可以了吧：
```.dockerfile
FROM node:21.6.2
```

或者需要通过全局的配置文件来管理部署多个项目吗

**Comment by hzh11012** [comment]
> 在我个人的认知里，感觉在`Docker`场景下应该不太需要这个功能吧，一般部署项目的时候该项目都会有一个`.dockerfile`文件，然后在该文件配置中指定`Nodejs`的版本就可以了吧：
> 
> ```dockerfile
> FROM node:21.6.2
> ```
> 
> 或者需要通过全局的配置文件来管理部署多个项目吗

是想着在linux机器上通过docker部署后，可以可视化进行管理大量node项目，比较方便

**Comment by 1111mp** [comment]
你说的应该是`Jenkins`吧，你可以使用`Jenkins`镜像结合环境变量来实现可视化管理不同的项目：

`.dockerfile`:
```.dockerfile
ARG NODE_VERSION
FROM node:$NODE_VERSION

ARG NODE_VERSION
ENV NODE_VERSION=$NODE_VERSION

// ...
```

然后`Jenkins`中配置`docker`相关的命令加上环境变量即可`--build-arg NODE_VERSION=$version`
