### ISSUE TITLE
 SSL 证书

### ISSUE THREAD

**Issue by lsrweb** [1111mp/nvm-desktop#68]
RequestError: write EPROTO 865216:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\..\third_party\boringssl\src\ssl\tls_record.cc:231:

**Comment by lsrweb** [comment]
![image](https://github.com/1111mp/nvm-desktop/assets/61956525/072ae6b8-81b4-41ca-a827-b9c015dfe438)

**Comment by lsrweb** [comment]
![image](https://github.com/1111mp/nvm-desktop/assets/61956525/fcbb4e92-dddb-4372-8ca2-268bdd7240d8)
意外发现,不只是ui出现了问题, 我的 yarn 也出现了问题

**Comment by 1111mp** [comment]
请问你是开了什么`vpn`吗 还是之前都正常只是安装`nvm-desktop`之后就这样了

这个错误是网络问题 你现在使用的下载镜像地址是什么 默认是`https://nodejs.org/dist` 你可以试试在浏览器中能否正常访问

如果不能的话试试更换镜像地址试试

`nvm-desktop`不会使用代理 所以这个错误你看看是否跟自己计算机的网络设置有关呢

**Comment by lsrweb** [comment]
https://nodejs.org/dist/ 这个网址访问没问题

**Comment by lsrweb** [comment]
代理也关闭了,也不大行,好奇怪

**Comment by 1111mp** [comment]
代理关闭之后重启一下电脑呢 有时候虽然关闭代理了但是网络的设置里面还是默认走的代理的设置（我就经常遇到这种问题 需要手动关闭http https socket这些代理的配置）

**Comment by lsrweb** [comment]
![image](https://github.com/1111mp/nvm-desktop/assets/61956525/e73335fe-6e03-4409-836c-a0d12abe8280)
ping 正常,

重启后依旧这样

**Comment by 1111mp** [comment]
想确认一下 是因为安装`nvm-desktop`之后就出现这个问题了 还是一开始`nvm-desktop`用起来是正常的

你试试将`https`换成`http`呢

我觉这个问题还是系统代理设置的问题 或者你直接安装`node`试试呢

或者你换一个镜像地址：`https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/`

**Comment by lsrweb** [comment]
在之前都没问题,然后今天我下载 vant 源码二开,使用 yarn 的时候才发现的问题,在这之前 pnpm 一直没问题

**Comment by 1111mp** [comment]
目前提供的信心不太好定位到具体的问题 但是这个应该和网络设置有关 根据你的错误提示 也有可能是`tls`的版本不一致导致`https`握手失败 而如果是代理（https代理到http服务）也会造成这个问题

（如果不是使用管理员权限打开的`nvm-desktop`，也可以试试使用管理员权限重新打开试试）

**Comment by lsrweb** [comment]
问题是高版本＞18的node不支持低版本的ssl，把node版本降下来就好了。

**Comment by 1111mp** [comment]
你切换到高版本的node之后就会出现这个问题吗（`macOS`不会出现这个问题） 那应该是和这里有关了：[got #2313](https://github.com/sindresorhus/got/pull/2313) 在`14`版本之后它开始不支持低版本（18版本）的LTS 

我目前身边没有`Windows`设备 没办法确定 抱歉

**Comment by 1111mp** [comment]
这个问题感觉是不是和电脑的`openssl`版本有关 应该可以通过升级电脑的`openssl`版本来解决这个问题？
