### ISSUE TITLE
能否支持cnpm yarn pnpm npx nvm 等包管理器

### ISSUE THREAD

**Issue by chenyueteng** [1111mp/nvm-desktop#69]
能否支持cnpm yarn pnpm npx nvm 等包管理器

问题： npm install pnpm -g  后  ，使用  pnpm  报  nvm-desktop: command not found: pnpm

**Comment by 1111mp** [comment]
支持的，这个信息提示你查看一下这里看能否帮助到你：(https://github.com/1111mp/nvm-desktop/issues/23)

**Comment by cn-liu** [comment]
我将npm全局依赖包指向一个固定的文件夹并且设置npm的config prefix 和环境变量，但依旧是nvm-desktop: command not found: ‘依赖包’ ，

**Comment by 1111mp** [comment]
@cn-liu 终端运行 npm config get prefix 输出什么，然后能够将还目录下的文件截图发出来看一下 

然后请确认将该目录添加到系统环境变量里面，且让其的优先级比 %HOMEPATH%\.nvmd\bin 高（即位置靠前）

**Comment by cn-liu** [comment]
@1111mp 感谢，已解决！，是环境变量的问题，原因是npm环境变量低于nvm环境变量找不到命令
