### ISSUE TITLE
The global npm package command cannot be used

### ISSUE THREAD

**Issue by lainbo** [1111mp/nvm-desktop#7]
I checked with `npm list -g --depth 0` to see that the node version is correct, and also installed the global packages I want, but none of the global commands for those packages work. Did I do something wrong?
![image](https://github.com/1111mp/nvm-desktop/assets/46062895/e233e9a0-53be-466d-814b-05545828ccd6)
![image](https://github.com/1111mp/nvm-desktop/assets/46062895/4e92a62f-a1b5-44ea-81eb-d074569a28c7)

---
I'm using Windows 11 22H2 22621.2361.
node is node 18.18.0 downloaded using nvm-desktop

**Comment by 1111mp** [comment]
Which version of nvm-desktop application are you using, and did you install the global package through `npm install yarn -g` command?

If everything goes well, the shim corresponding to the global package should be added to your file directory: `%HOMEPATH%/.nvmd/bin/yarn.exe` & `%HOMEPATH%/.nvmd/bin/yarn.cmd`.

<img width="868" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/31227919/94982908-f0ac-4df5-81bd-f6b8643314d4">

(Forgive me for the Macos use case, but the situation on Windows platform is similar)

Maybe you can check the system environment variables: `%HOMEPATH%/.nvmd/bin` or run `nvmd -h`check if it takes effect.
