### ISSUE TITLE
循环查找父级的.nvmdrc

### ISSUE THREAD

**Issue by JS-an** [1111mp/nvm-desktop#71]
![image](https://github.com/1111mp/nvm-desktop/assets/25688878/ba2e0800-e6a3-4007-9b7b-a0fbec9e440b)
我有一个这样的结构
我在 /test 下 node -v 是正常的 版本为 V18.XX.XX
但如果我在 /test/server 下  node -v 是显示全局默认版本 版本为 V20.XX.XX
可不可以在 /test/server  下也使用  /test 的 .nvmdrc

**Comment by 1111mp** [comment]
请问你现在使用的nvm-desktop的版本是多少，最新的Release 3.2.0已经支持这个功能了。你试试更新到最新版本之后再试试呢。

**Comment by 1111mp** [comment]
终端执行nvmd -h并截图看一下呢

**Comment by JS-an** [comment]
![image](https://github.com/1111mp/nvm-desktop/assets/25688878/789d6e95-be9e-4726-bd54-c5b1d188dde8)


> 终端执行nvmd -h并截图看一下呢

**Comment by 1111mp** [comment]
这就很奇怪了 我按照你的目录结构在本地测试了一下是正常的：

![image](https://github.com/1111mp/nvm-desktop/assets/31227919/2c95ca2f-76a1-4eac-b8a3-62c0d7fb1181)

![image](https://github.com/1111mp/nvm-desktop/assets/31227919/e58cd5be-f737-463a-8f43-9322c460bf87)

你尝试一下将`%HOMEPATH%\.nvmd\bin`目录下的`node.exe`删除，然后再复制`nvmd.exe`并重命名为`node.exe`。然后再试试能否识别。

**Comment by JS-an** [comment]
找到问题了，之前使用nvm安装的版本文件夹是带着一个 v 的
而我们的安装是没有 v 的
我之前直接文件名使用了 v18.18.2 改成 18.18.2 就可以了
谢谢大佬的帮助！！！
![image](https://github.com/1111mp/nvm-desktop/assets/25688878/d5d7c3be-5bb6-4063-9ff2-8e98ef050aab)

**Comment by JS-an** [comment]
![image](https://github.com/1111mp/nvm-desktop/assets/25688878/b667cbb5-d116-4cd9-b5d1-6006608d43a7)


> 找到问题了，之前使用nvm安装的版本文件夹是带着一个 v 的 而我们的安装是没有 v 的 我之前直接文件名使用了 v18.18.2 改成 18.18.2 就可以了 谢谢大佬的帮助！！！ ![image](https://private-user-images.githubusercontent.com/25688878/312391515-d5d7c3be-5bb6-4063-9ff2-8e98ef050aab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjE5NzEsIm5iZiI6MTcxMDMyMTY3MSwicGF0aCI6Ii8yNTY4ODg3OC8zMTIzOTE1MTUtZDVkN2MzYmUtNWJiNi00MDYzLTlmZjItOGU5OGVmMDUwYWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5MjExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNjYwNzE1YTFlNWE1MjBhMTE1ZWNlMGU0ZDVlM2FmM2JlYWUyMDI3MGRmYWI3OTg3OThlMWU0MTNjNGU4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.urojP0TEN2Kq7jMIxa7j_NXZM2yOMZAQcgHq3mnI6gw)

**Comment by 1111mp** [comment]
好的 问题解决了就好 🌹 

那么我就先将这个`issue`关闭了 当然后续如果有任何问题都可以随时重新打开 谢谢
