### ISSUE TITLE
能自动读取 .nvmdrc 中的node版本吗? 

### ISSUE THREAD

**Issue by xiaomu-dev** [1111mp/nvm-desktop#72]

**Comment by 1111mp** [comment]
不太能理解你的意思...

不过`.nvmdrc`文件是用来为`project`来指定`nodejs`版本的，当你在某个目录下设置过`.nvmdrc`文件（只需要设置一次即可），那么在此目录下的`nodejs`的版本就会是`.nvmdrc`文件中设置的版本，这一切都是自动的，不需要用户参与。
