### ISSUE TITLE
360报毒

### ISSUE THREAD

**Issue by godcop** [1111mp/nvm-desktop#73]
如题

**Comment by 1111mp** [comment]
因为打包的时候都没有证书签名（证书都是付费的），所以这些杀毒软件可能会提示安全风险。但是`nvm-desktop`代码完全开源，安全方面的问题你可以完全放心，你也可以根据文档 [build-and-package](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#build-and-package) 将代码拉到本地自己编译然后安装。

所以需要你在杀毒软件中选择信任此软件即可。
