### ISSUE TITLE
命令不起作用

### ISSUE THREAD

**Issue by AisinGioroZhang** [1111mp/nvm-desktop#74]
v16.20.2设为了全局， nvmd node 输入后，没反应 命令行直接下一行了。

**Comment by 1111mp** [comment]
终端输入node --version也没反应吗

**Comment by AisinGioroZhang** [comment]
是的，很奇怪，我之前电脑是win11，正常使用，刚换了一个win10，试了node -v, PS C:\Users\Administrator> node --version
PS C:\Users\Administrator> nvmd -h
PS C:\Users\Administrator>

**Comment by 1111mp** [comment]
试试输入其它命令看能不能做行呢，比如：ipconfig

**Comment by AisinGioroZhang** [comment]
其他的是可以的，这个电脑有360，我卸载试试吧，我看其他issue有说360的问题。

**Comment by 1111mp** [comment]
你检查一下系统环境变量，是否有添加%HOMEPATH%\.nvmd\bin。如果没问题试试终端直接使用node test.js运行js文件，看会不会运行呢

**Comment by AisinGioroZhang** [comment]
解决了，我刚才是在powershell和gitbash下输入的命令没反应，换了cmd ,报错缺少xxx.dll,然后360自动弹框帮我下载vc++ 合集，再运行就好了

**Comment by 1111mp** [comment]
好的，问题解决了就好。👍

**Comment by 1111mp** [comment]
那么我就先把这个issue关掉了，当然后续如果有问题可以随时重新打开，谢谢。
