### ISSUE TITLE
接口请求超时?

### ISSUE THREAD

**Issue by SeaAster** [1111mp/nvm-desktop#75]
没有使用vpn, 所有版本是一样的问题
![6692fb9e3b1ee2f256a5058307093a4](https://github.com/1111mp/nvm-desktop/assets/54931083/bf1b7337-c9a4-4f3a-9c8c-304168bad40a)
![f74f986ac6bfaddcde8c75cf516aa22](https://github.com/1111mp/nvm-desktop/assets/54931083/eb9260ca-fc21-49c0-950e-c972673b45e2)

**Comment by 1111mp** [comment]
你可以尝试换一个镜像地址试试呢 比如：https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/

然后你可以试试将一直超时的地址在浏览器中打开看能不能访问

建议是使用最新的版本

**Comment by SeaAster** [comment]
> 你可以尝试换一个镜像地址试试呢 比如：https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/
> 
> 然后你可以试试将一直超时的地址在浏览器中打开看能不能访问
> 
> 建议是使用最新的版辛苦了，新的镜像可以使用

**Comment by SeaAster** [comment]
> 你可以尝试换一个镜像地址试试呢 比如：https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/
> 
> 然后你可以试试将一直超时的地址在浏览器中打开看能不能访问
> 
> 建议是使用最新的版本

辛苦了，新的镜像可以用，感谢

**Comment by 1111mp** [comment]
好的 问题解决了就好 🌹 

那么我就先把这个`issue`关闭了 当然后续如果还有任何问题都可以随时重新打开此`issue` 谢谢
