### ISSUE TITLE
npm link无效

### ISSUE THREAD

**Issue by AprilLemon** [1111mp/nvm-desktop#78]
自己写了一个脚手架test-cli，用npm link到全局，npm ls -g 中存在test-cli，但是执行test-cli无效，无法将“test-cli”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再
试一次。。另外一台电脑直接安装官方node版本包，测试结果是正常的。

**Comment by AprilLemon** [comment]
> 我自己在本地试了一下，是可以正常工作的。
> 
> 工作目录：
> 
> ```
> |-- linker
>     |-- package.json
>     |-- index.mjs
> |-- project
>     |-- index.mjs
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/31227919/324403721-91b98b90-b032-4eb3-b033-05f618128a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MzYzMzksIm5iZiI6MTcxMzgzNjAzOSwicGF0aCI6Ii8zMTIyNzkxOS8zMjQ0MDM3MjEtOTFiOThiOTAtYjAzMi00ZWIzLWIwMzMtMDVmNjE4MTI4YTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAxMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNmMwMzI4MjY5NjUyMzA5YjA0ZjllMzM3Yzk4NmM0OTI0YmE1NzQ0ZTA0ZTcyZmJlMTU3MTM0ZGVhN2VhNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yOcHqoG9v7-AEa5TK17oLSCH202rADMtY9yvLSdjp6A)
> 
> `linker/*`:
> 
> ```js
> // package.json
> {
>   "name": "linker",
>   "version": "1.0.0",
>   "description": "npm link test",
>   "main": "index.mjs",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "author": "",
>   "license": "ISC",
>   "dependencies": {}
> }
> 
> // index.mjs
> export function add(a, b) {
>   return a + b;
> }
> ```
> 
> `project/index.mjs`:
> 
> ```js
> import { add } from 'linker';
> 
> const ret = add(1, 2);
> 
> console.log(ret);
> ```
> 
> * `"linker/"` 目录下执行 `npm link`
> * `"project/"` 目录下执行 `npm link linker`
> * `"project/"` 目录下执行 `node index.mjs`
> 
> 结果如下：
> 
> ![image](https://private-user-images.githubusercontent.com/31227919/324404835-369633bd-b8b2-4a2f-840b-519393807e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MzYzMzksIm5iZiI6MTcxMzgzNjAzOSwicGF0aCI6Ii8zMTIyNzkxOS8zMjQ0MDQ4MzUtMzY5NjMzYmQtYjhiMi00YTJmLTg0MGItNTE5MzkzODA3ZTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAxMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3M2RlMTBiZDUzNDM0ZjAyYWNmN2RmZDc1MmQyOWI4MTE5NjczYjU5MzA3ZDMyNzdhOTQ0NjA0ZmZjYTkxNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kS7ELlOK6NifY8VH85wY8GV7-zqR_374PAUsspPqlww)
> 
> 请问你在`link`之后切换了`node`的版本吗，因为`nvm-desktop`在设计的时候是保持每个`node`版本之间相互隔离的，所以如果中间切换了版本，请重新`link`一下。

感谢，已解决，当前项目选用版本后，需要将该版本放入系统path中。

**Comment by 1111mp** [comment]
感谢你的回复，不过经过本地测试这确实是一个bug。

在执行`npm link`添加全局包的时候确实需要跟踪并添加一个`shim`到`%HOMEPATH%\.nvmd\bin\`目录下，这个我后续支持一下，得先学习一下`npm link/unlink`命令的文档。

我先把这个`issue`重启开启，后续支持`npm link/unlink`的命令之后再关闭，请知悉。

**Comment by 1111mp** [comment]
目前在最新的 [Release v3.3.0](https://github.com/1111mp/nvm-desktop/releases/tag/v3.3.0) 中已经修复了这个问题，支持 npm 的 `link` & `unlink` & `update` 命令

那么我就先将此 `issue` 关闭了，当然后续如果有任何问题都可以随时重新开启，谢谢 🌹
