### ISSUE TITLE
RequestError: unable to verify the first certificate

### ISSUE THREAD

**Issue by zangxycoding** [1111mp/nvm-desktop#81]
系统：Win 专业版 21H2

刚装的新系统

- 关闭代理无效
- 切换镜像地址无效
- 以管理员模式重新安装或运行无效

![image](https://github.com/1111mp/nvm-desktop/assets/17939214/b0d4f4cd-3022-4632-bc3a-2106ec871412)

**Comment by 1111mp** [comment]
试试这个镜像地址呢：https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/

**Comment by zangxycoding** [comment]
> 试试这个镜像地址呢：https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/

还是不行，镜像地址浏览器访问都是没问题的，我怀疑的操作系统的网络策略问题，实在不行只能重装了

**Comment by 1111mp** [comment]
我觉得是不是代理并没有完全关闭，或者是DNS缓存造成的，你试试：

- 参考https://jingyan.baidu.com/article/e75aca853fedbc552fdac619.html关闭系统代理
- 清除DNS缓存，终端运行 `ipconfig /flushdns`

可能需要重启电脑。

**Comment by zangxycoding** [comment]
> 我觉得是不是代理并没有完全关闭，或者是DNS缓存造成的，你试试：
> 
> * 参考[https://jingyan.baidu.com/article/e75aca853fedbc552fdac619.html关闭系统代理](https://jingyan.baidu.com/article/e75aca853fedbc552fdac619.html%E5%85%B3%E9%97%AD%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86)
> * 清除DNS缓存，终端运行 `ipconfig /flushdns`
> 
> 可能需要重启电脑。

重装了win10 能用了..
