### ISSUE TITLE
RequestError: unable to verify the first certificate

### ISSUE THREAD

**Issue by zane0904** [1111mp/nvm-desktop#82]
w10专业版 出现这个提示是什么意思呢 我看了之前的issue没找到解决办法
![image](https://github.com/1111mp/nvm-desktop/assets/41895910/aab0686b-3a5d-4789-a4d6-4e67d7d5c38e)

**Comment by 1111mp** [comment]
这个是证书验证失败 之前的issue跟电脑的环境环境有关，一般是网络相关的设置不正确或者使用VPN造成的

获取你可以查看一下这里：https://github.com/sindresorhus/got/issues/675#issuecomment-447334472

目前`nvm-desktop`中使用的就是`got`

**Comment by zane0904** [comment]
好的 谢谢

**Comment by zane0904** [comment]
> 这个是之前的证书验证失败的问题跟电脑的环境环境有关，一般是网络相关的设置不正确或者使用VPN造成的
> 
> 或者你可以在这里查看一下：[sindresorhus/got#675 (comment)](https://github.com/sindresorhus/got/issues/675#issuecomment-447334472)
> 
> 目前`nvm-desktop`中使用的就是`got`

好的 谢谢
