### ISSUE TITLE
全局安装pnpm报错

### ISSUE THREAD

**Issue by djkloop** [1111mp/nvm-desktop#84]
#### 环境信息
![image](https://github.com/1111mp/nvm-desktop/assets/21050914/54bbc7d7-36e9-434a-86c7-9393d10a498f)

#### 报错信息
![image](https://github.com/1111mp/nvm-desktop/assets/21050914/8263b2dc-11a3-4aa4-98f5-e30fd72d536d)

**Comment by 1111mp** [comment]
这个报错是因为 `"%HOMEPATH%\.nvmd\bin\nvmd.exe"` 文件不存在，你可以打开这个目录看一下 `nvmd.exe` 文件是否真的不存在

如果文件丢失的话 估计和这里的情况一致：(https://github.com/1111mp/nvm-desktop/issues/70)

目前的话针对这个问题应该在下个版本会修复（具体原因还没确定到，因为他们没有给后续的反馈....），你也可以从这里找到相关的代码提交：(https://github.com/1111mp/nvm-desktop/pull/83)

目前的临时解决方案就是你在 `"%HOMEPATH%\.nvmd\bin\nvmd.exe"`  目录下复制一个 `.exe` 文件（该目录下的`.exe`结尾的文件，因为他们都是从`nvmd.exe`复制过去的），然后重命名为 `nvmd.exe` 就行了。
