### ISSUE TITLE
关于卸载node报错

### ISSUE THREAD

**Issue by BG7ZAG** [1111mp/nvm-desktop#85]
![微信截图_20240511095927](https://github.com/1111mp/nvm-desktop/assets/16408650/6f9e3ef7-907d-49d5-95d2-8157f59a9e7f)

点击卸载，等了一会看没反应，再点一次，就出现这个错误了。

刷新view后再次点击也报这个错误。估计是刚开始点两下卸载导致的

**Comment by 1111mp** [comment]
是不是有项目在运行 导致被占用 所以无法卸载

**Comment by BG7ZAG** [comment]
> 是不是有项目在运行 导致被占用 所以无法卸载

还真是，忘了关某个项目了
![05780B7F](https://github.com/1111mp/nvm-desktop/assets/16408650/b14cfe6c-79f0-4d29-a6e4-c478f37e71fa)
