### ISSUE TITLE
为什么安装yarn后不能使用，提示nvm-desktop: command not found: "yarn"

### ISSUE THREAD

**Issue by g12201** [1111mp/nvm-desktop#86]
![image](https://github.com/1111mp/nvm-desktop/assets/147135199/09113a70-9fd0-453f-9437-b51fcee310d5)
这是.nvmd\bin下的目录，
npm install yarn -g 全局安装。
重启后，或者在环境变量中加入yarn的bin也无法使用，
请问是哪里操作不对呢？

**Comment by 1111mp** [comment]
你看这里能帮助到你吗 https://github.com/1111mp/nvm-desktop/issues/69

**Comment by geniyangge** [comment]
我也遇到了这个问题

**Comment by 1111mp** [comment]
请确认如果更改了全局安装包的路径 那么需要将其添加到系统环境变量里面去 可参考：https://github.com/1111mp/nvm-desktop/issues/23
