### ISSUE TITLE
nvm-desktop: command not found: vue

### ISSUE THREAD

**Issue by lebRonFeng** [1111mp/nvm-desktop#88]
nvm-desktop: command not found: vue

**Comment by lebRonFeng** [comment]
After installing nvm desktop by default, node version 14.16.0 was installed, followed by setting up Taobao images and installing Vue globally, which resulted in the following situation

**Comment by 1111mp** [comment]
- First you need to check whether you have changed the installation directory of npm's global package: `npm config get prefix`
- If you do this, you should add the directory to your system's environment variables.(Make sure the priority is higher than `HOMEPATH\.nvmd\bin`)

You can find more detailed instructions here: (https://github.com/1111mp/nvm-desktop/issues/23)
