### ISSUE TITLE
期望兼容nvm

### ISSUE THREAD

**Issue by 2331892928** [1111mp/nvm-desktop#89]
以前已经用nvm进行了管理，现在想用desktop，但是这个项目貌似不支持nvm，只支持nvmd

**Comment by 1111mp** [comment]
其实这个问题在一开始的时候也考虑过，但是最终觉得还是应该跟 `nvm` 分开，主要有这些原因吧：

- `nvm-desktop`和`nvm`的底层实现完全不一样（`nvm`主要依赖`shell`，`nvm-desktop`是通过`rust`开发的一个代理程序来实现）
- 使用方式有区别，`nvm-desktop`使用可视化界面的方式 `nvm`使用终端工具命令行 因为`nvm-desktop`其实对于命令行工具不是强依赖 所以一开始设计的时候没有提供这个`nvmd`命令行工具 后面为了使用更方便 所以才加上的
- 不想与`nvm`有冲突 所以用户可以在电脑上同时安装和使用`nvm-deskop`和`nvm` 所以使用`nvmd`与其区分开

还望理解。谢谢 🌹

**Comment by fu827707013** [comment]
之前用nvm安装了好多个node版本，现在用desktop，怎么将原来的node安装路径应用到desktop呢，node版本不想一个个重装
