### ISSUE TITLE
能直接在项目中直接点击启动吗？

### ISSUE THREAD

**Issue by theDoinb** [1111mp/nvm-desktop#90]
就直接弹出cmd启动就行了

**Comment by 1111mp** [comment]
没能理解你的意思 是说在项目中直接通过某种方式启动`nvm-desktop`客户端吗

切换node的版本可以不强依赖客户端 你也可以通过命令行工具的命令来切换`node`的版本 你可以在终端中输入`nvmd --help`查看完整的提示信息，也可以从这里获取文档说明：(https://github.com/1111mp/nvmd-command#command-tools-intro)

**Comment by theDoinb** [comment]
额，windows我打开了程序，意思是上面tab项目，切到该页时，下边是我添加的本地项目的表格，操作栏有个启动就好了，可以给自定义Shell也行，便于给运维那边用

**Comment by theDoinb** [comment]
我想了想，就是例如我给个打包按钮`yarn build`，启动按钮`yarn start`啥的，每次都先变更了node版本再使用，或者仅对当前使用该node版本...

**Comment by 1111mp** [comment]
不好意思这么久才回复。
感觉这个功能有点超出范围了😂 如果是作为那边使用的话，完全可以写一个CI脚本来实现的。

**Comment by theDoinb** [comment]
> 不好意思这么久才回复。 感觉这个功能有点超出范围了😂 如果是运维那边使用的话，完全可以写一个CI脚本来实现的。

ok，就随便问问
