### ISSUE TITLE
项目路径太长表格文字没对齐

### ISSUE THREAD

**Issue by lsrweb** [1111mp/nvm-desktop#91]
![image](https://github.com/1111mp/nvm-desktop/assets/61956525/107671b8-6c35-4296-a770-25f6f73cc154)

**Comment by 1111mp** [comment]
好的 谢谢指出这个问题 

问题已经记录下来了 等下个小版本会修复这个问题 谢谢 🌹

**Comment by lsrweb** [comment]
🌹🌹🌹

**Comment by 1111mp** [comment]
抱歉啊 这个问题还没修复 因为目前主要的精力都放在 tauri 的重构上了（平时上班也有点忙），所以没有及时修复，抱歉。

**Comment by lsrweb** [comment]
支持代理了,这个好啊,没事,都是小问题
