### ISSUE TITLE
低版本不支持怎么手动添加

### ISSUE THREAD

**Issue by jinHua-96** [1111mp/nvm-desktop#94]
mac  低版本不支持怎么手动添加

**Comment by 1111mp** [comment]
你看一下这里能不能帮助你：(https://github.com/1111mp/nvm-desktop/issues/13#issuecomment-1813792176)

**Comment by 1111mp** [comment]
你的是macos吧，然后arm架构？你下载的这个是什么系统和架构，macos和windows的node目录结构不一样，这边是通过node的执行文件是否存在来判断安装的

**Comment by jinHua-96** [comment]
ARM架构 M芯片
<img width="1310" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/121592065/c9a6167f-18f8-4709-98bf-084551bf9658">
https://github.com/nodejs/node/releases/tag/v13.14.0 这里下的

**Comment by 1111mp** [comment]
你可以从这里下载 [https://nodejs.org/dist/v13.14.0/](https://nodejs.org/dist/v13.14.0/) 
![image](https://github.com/1111mp/nvm-desktop/assets/31227919/0027def9-6474-4b7b-9c50-5c6070a9bac2)

解压之后在 `13.14.0/bin/` 目录下是否有 `node` 这个文件

**Comment by 1111mp** [comment]
你可以从这里下载 [https://nodejs.org/dist/v13.14.0/](https://nodejs.org/dist/v13.14.0/) 
![image](https://github.com/1111mp/nvm-desktop/assets/31227919/0027def9-6474-4b7b-9c50-5c6070a9bac2)

解压之后在 `13.14.0/bin/` 目录下是否有 `node` 这个文件

**Comment by jinHua-96** [comment]
非常感谢 可以了

**Comment by 1111mp** [comment]
好的，问题解决了就好，那我这边先把这个问题关闭了。当然后续如果还有问题可以随时重新打开这个问题的。谢谢🌹
