### ISSUE TITLE
mac m1 显示 文件已损坏

### ISSUE THREAD

**Issue by davy-gan** [1111mp/nvm-desktop#95]
<img width="508" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/21240946/2044c8e5-c5fb-45e3-aea6-9cd9da9d73c2">
<img width="338" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/21240946/76930c3e-1a21-44be-bbed-1c67d828a178">
版本3.3.0

**Comment by 1111mp** [comment]
因为目前打包的时候没有证书进行签名导致的（Apple开发者账号，需要付费），解决方案可以参考文档：[nvm-desktop macos-issues](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#macos-issues)

代码完全开源，所以放心信任并孕育 nvm-desktop 的运行，当然如果还是觉得担心，也可以根据文档自己编译：[develop-and-build](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#develop-and-build)

谢谢

**Comment by davy-gan** [comment]
<img width="1085" alt="image" src="https://github.com/1111mp/nvm-desktop/assets/21240946/9755191b-f65c-4680-8962-3a1d67807bc3">
按照这个方式安装成功 但是node 找不到是为什么呢
