### ISSUE TITLE
新版 windows 11 23H2 无法使用

### ISSUE THREAD

**Issue by sunsboyxu** [1111mp/nvm-desktop#97]
新版 windows 11 23H2 无法使用，windows 系统是最新安装了，下载了 nvm-desktop 3.2.0 版本的，安装没问题，使用时没反应
nvmd list 无法使用 node 安装可以，node -v 无法使用
![屏幕截图 2024-06-20 215654](https://github.com/1111mp/nvm-desktop/assets/25958787/715b65ea-18e2-470a-9c8b-e023ca78d77d)

**Comment by 1111mp** [comment]
如果是新安装的windows系统的话 是不是因为缺少 `VCRUNTIME140.dll` 文件 你可以尝试使用 `cmd` 运行这些命令 如果是这个问题造成的话可以在这个地址下载安装该文件：[Microsoft Visual C++ Redistributable 下载页面](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

（如果你使用了一些第三方安全软件的话 建议先关闭安全软件或者加入白名单再运行）

如果这些都解决不了的话 你先阅读一下这个文档：[nvm-desktop somethings-you-need-to-know](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#maybe-somethings-you-need-to-know) 然后确认一下这些文件是否都存在 最后就是确认一下是否加入到系统环境变量
