### ISSUE TITLE
Error invoking remote method 'check-for-updates': TypeError: Object has been destroyed

### ISSUE THREAD

**Issue by chenlimao** [1111mp/nvm-desktop#98]
Error invoking remote method 'check-for-updates': TypeError: Object has been destroyed

**Comment by 1111mp** [comment]
What version are you using?
This issue has been fixed in [Release v3.0.0](https://github.com/1111mp/nvm-desktop/releases/tag/v3.0.0).

The current solution is to re-enable `nvm-desktop` and then click Check for Updates (The first time after restart is effective).

**Comment by chenlimao** [comment]
Release v3.3.0，退出软件重启解决问题了
