### ISSUE TITLE
安装后所有版本为空

### ISSUE THREAD

**Issue by limengyin-sudo** [1111mp/nvm-desktop#99]
![image](https://github.com/user-attachments/assets/44f6b24c-5be3-4357-aacd-13d5b50907b6)

**Comment by Xiangzi529** [comment]
卸载不干净

**Comment by Xiangzi529** [comment]
我现在卸载了 node也没了 一直报  node -v
nvm-desktop: command not found: "node"

**Comment by 1111mp** [comment]
@Xiangzi529 因为用的手机，打字不方便，望理解。

项目github的readme文档上写有关于如何卸载nvm-desktop，可以去看看呢，谢谢
